### ISSUE TITLE
Issue: YACE periodically crashes in K8S

### ISSUE THREAD

**Issue by Jasstkn** [ivx/yet-another-cloudwatch-exporter#100]
Hi!
I run YACE as service in K8S, but it periodically crashes by some reasons and I can't understand where is problem.
There are some logs from internal Kibana. Maybe you have ideas, what is going on?

```
September 19th 2019, 10:02:33.701 | goroutine 267045 [running]:

  | September 19th 2019, 10:02:33.701 | main.cloudwatchInterface.get(0xc3c300, 0xc0000ea648, 0xc00044cd00, 0xc0004706f0, 0xc0000975f0, 0x9)

  | September 19th 2019, 10:02:33.701 |  

  | September 19th 2019, 10:02:33.701 | /opt/aws_cloudwatch.go:139 +0x170
  | September 19th 2019, 10:02:33.701 | /opt/abstract.go:172 +0x2af

  | September 19th 2019, 10:02:33.701 | 2019/09/19 10:02:24 Parse config..

  | September 19th 2019, 10:02:33.701 | caused by: Post https://monitoring.us-east-1.amazonaws.com/: read tcp 10.4.211.144:46962->52.94.238.156:443: read: connection reset by peer

  | September 19th 2019, 10:02:33.701 | 2019/09/19 10:02:24 Startup completed

  | September 19th 2019, 10:02:33.701 | /opt/abstract.go:146 +0x18b

  | September 19th 2019, 10:02:33.701 | created by main.scrapeDiscoveryJob.func2

  | September 19th 2019, 10:02:33.701 | main.scrapeDiscoveryJob.func2.1(0xc000464180, 0xc0005812c0, 0xc000062300, 0x109b3a8, 0x0, 0x0, 0xc0000eaa70, 0x1, 0x1, 0xc0006f2600, ...)

  | September 19th 2019, 10:02:33.701 | panic: RequestError: send request failed

  | September 19th 2019, 08:18:31.840 | 2019/09/19 08:18:24 Startup completed

  | September 19th 2019, 08:18:31.782 |  

  | September 19th 2019, 08:18:31.782 | /opt/abstract.go:172 +0x2af

  | September 19th 2019, 08:18:31.782 | created by main.scrapeDiscoveryJob.func2

  | September 19th 2019, 08:18:31.782 | panic: RequestError: send request failed

  | September 19th 2019, 08:18:31.782 | main.scrapeDiscoveryJob.func2.1(0xc000472130, 0xc0008b6c30, 0xc0006b7620, 0x109b3a8, 0x0, 0x0, 0xc00010a0e8, 0x1, 0x1, 0xc0008a2240, ...)

  | September 19th 2019, 08:18:31.781 | /opt/aws_cloudwatch.go:139 +0x170

  | September 19th 2019, 08:18:31.781 | 2019/09/19 08:18:24 Parse config..

  | September 19th 2019, 08:18:31.781 | caused by: Post https://monitoring.us-east-1.amazonaws.com/: read tcp 10.4.211.144:59326->52.94.238.156:443: read: connection reset by peer

  | September 19th 2019, 08:18:31.781 | goroutine 1968659 [running]:

  | September 19th 2019, 08:18:31.781 | main.cloudwatchInterface.get(0xc3c300, 0xc0001c6028, 0xc000bc4280, 0xc0003ac960, 0xc000097760, 0xf)

  | September 19th 2019, 08:18:31.781 | /opt/abstract.go:146 +0x18b

  | September 18th 2019, 19:32:33.964 | /opt/abstract.go:146 +0x18b

  | September 18th 2019, 19:32:33.896 | created by main.scrapeDiscoveryJob.func2

  | September 18th 2019, 19:32:33.896 |  

  | September 18th 2019, 19:32:33.896 | goroutine 67201 [running]:

  | September 18th 2019, 19:32:33.896 | /opt/aws_cloudwatch.go:139 +0x170

  | September 18th 2019, 19:32:33.896 | main.scrapeDiscoveryJob.func2.1(0xc00032c1a0, 0xc000287e00, 0xc000062540, 0x109b3a8, 0x0, 0x0, 0xc00000ecf0, 0x1, 0x1, 0xc00062aae0, ...)

  | September 18th 2019, 19:32:33.896 | caused by: Post https://monitoring.us-east-1.amazonaws.com/: read tcp 10.4.211.144:36196->52.94.238.156:443: read: connection reset by peer

  | September 18th 2019, 19:32:33.896 | /opt/abstract.go:172 +0x2af

  | September 18th 2019, 19:32:33.896 | main.cloudwatchInterface.get(0xc3c300, 0xc00000e5b0, 0xc0001e1a00, 0xc00048a650, 0xc0001b22e0, 0xb)

  | September 18th 2019, 19:32:33.896 | 2019/09/18 19:32:24 Parse config..

  | September 18th 2019, 19:32:33.896 | 2019/09/18 19:32:24 Startup completed

  | September 18th 2019, 19:32:33.896 | panic: RequestError: send request failed

  | September 18th 2019, 19:06:23.712 | panic: RequestError: send request failed
  | September 18th 2019, 19:06:23.712 | /opt/abstract.go:146 +0x18b

  | September 18th 2019, 19:06:23.712 | main.cloudwatchInterface.get(0xc3c300, 0xc0001a0050, 0xc000996400, 0xc000476910, 0xc0001d6800, 0xf)
  | September 18th 2019, 19:06:23.712 | /opt/abstract.go:172 +0x2af

  | September 18th 2019, 19:06:23.712 | created by main.scrapeDiscoveryJob.func2

  | September 18th 2019, 19:06:23.712 | main.scrapeDiscoveryJob.func2.1(0xc000444210, 0xc0006e4570, 0xc000356ae0, 0x109b3a8, 0x0, 0x0, 0xc0001c2348, 0x1, 0x1, 0xc00089a240, ...)

  | September 18th 2019, 19:06:23.712 | /opt/aws_cloudwatch.go:139 +0x170

  | September 18th 2019, 19:06:23.712 |  

  | September 18th 2019, 19:06:23.711 | caused by: Post https://monitoring.us-east-1.amazonaws.com/: read tcp 10.4.211.144:46214->52.94.238.156:443: read: connection reset by peer

  | September 18th 2019, 19:06:23.711

```

Also there are a lot of messages with following content:
```
2019/09/19 10:02:24 WATCH OUT! - Metric length of less than 5 minutes configured which is default for most cloudwatch metrics e.g. ELBs
```
What is this about?

Describe pod from kubectl
```
Controlled By:        ReplicaSet/yace-76b78d77d4
Containers:
  yace:
    Container ID:  docker://07133d395a18dcfeb4897076634cce4ff5c50147fbd7d9664de038db62f2d698
    Image:         quay.io/invisionag/yet-another-cloudwatch-exporter:v0.14.0-alpha
    Image ID:      docker-pullable://quay.io/invisionag/yet-another-cloudwatch-exporter@sha256:6bbc0b7e7b0e85029522772436382d5d653e775aae44f4775e908e261ba80fdc
    Port:          5000/TCP
    Host Port:     0/TCP
    Args:
      --config.file=/tmp/config.yml
    State:          Running
      Started:      Thu, 19 Sep 2019 13:02:24 +0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 19 Sep 2019 11:18:24 +0300
      Finished:     Thu, 19 Sep 2019 13:02:24 +0300
    Ready:          True
    Restart Count:  41
    Limits:
      cpu:     500m
      memory:  256Mi
    Requests:
      cpu:        200m
      memory:     128Mi
    Liveness:     http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wwsjx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      yace-config
    Optional:  false
```

And sample of config:
```
config:
  discovery:
    jobs:
    - type: "ec"
      region: us-east-1
      metrics:
      - name: NewConnections
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: CurrConnections
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: GetTypeCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: SetTypeCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: CacheMisses
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: CacheHits
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: CPUUtilization
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: EngineCPUUtilization
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: FreeableMemory
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: UnusedMemory
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: SwapUsage
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: GetTypeCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: GetTypeCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: HashBasedCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: ListBasedCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: SetBasedCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: SetTypeCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: SortedSetBasedCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: StringBasedCmds
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: SaveInProgress
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: CurrItems
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: BytesUsedForCache
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: ReplicationBytes
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: NetworkBytesIn
        statistics:
        - 'Average'
        period: 300
        length: 300
      - name: NetworkBytesOut
        statistics:
        - 'Average'
        period: 300
        length: 300
```
