### ISSUE TITLE
0.14.1 regression

### ISSUE THREAD

**Issue by ywliu** [ivx/yet-another-cloudwatch-exporter#102]
With these simple metrics :
``` YAML
discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
  jobs:
    - region: ap-northeast-1
      type: ec2
      searchTags:
        - Key: d2nova:common:project
          Value: evox
        - Key: d2nova:common:environment
          Value: prod
      metrics:
        - name: DiskSpaceUtilization
          statistics:
            - Average
          period: 600
          length: 3600
          additionalDimensions:
            - name: MountPath
              value: /
        - name: NetworkIn
          statistics:
            - Maximum
          period: 60
          length: 600
        - name: NetworkOut
          statistics:
            - Maximum
          period: 60
          length: 600
```

With 0.14.0, I can get all of them. But after I upgrade to 0.14.1, NetworkIn and NetworkOut are no longer generated.

I suspect it's because of the introduction of awsDimension interferring with additionalDimensions in the DiskSpaceUtilization beforehand.

**Comment by thomaspeitz** [comment]
Thanks for reporting this. Will dig into it.

**Comment by AceHack** [comment]
I am having a very similar issue.  The following works if I remove awsDimensions but does not work if I leave it in.  Latency metric works with no issues either way.

```
  discovery:
    exportedTagsOnMetrics:
      elb:
        - kubernetes.io/service-name
        - AssetID
        - AssetName
    jobs:
    - type: elb
      region: us-east-1
      awsDimensions:
       - AvailabilityZone
      searchTags:
        - Key: AssetID
          Value: 2269
      metrics:
        - name: HTTPCode_ELB_4XX
          statistics:
          - Sum
          period: 60
          length: 600
          delay: 60
          nilToZero: true
```
