### ISSUE TITLE
ecs-svc discovery doesnt scrape anything

### ISSUE THREAD

**Issue by dnull88** [ivx/yet-another-cloudwatch-exporter#123]
Basic config:
`discovery:

  jobs:
  - region: us-east-1
    type: ecs-svc
    metrics:
      - name: CPUUtilization
        statistics:
        - Average
        period: 600
        length: 60
`

doesnt scrape any metrics from cloudwatch. I activated debug mode, but nothing in logs. With static config all is ok.

**Comment by thomaspeitz** [comment]
I think you are missing tags for discovery of your svc:
```
    searchTags:
      - Key: type
        Value: ^(easteregg|k8s)$
```

**Comment by dnull88** [comment]
Fixed in new release (v0.14.6-alpha). Thanks

**Comment by daviddetorres** [comment]
Hi, I'm trying to scrape ECS metrics with the static configuration to get Fargate statistics, but nothing appears... I'm using this configuration: 

```
static:
  - namespace: ECS/ContainerInsights
    name: fargate
    region: us-east-1
    dimensions:
      - name: ClusterName
    metrics:
      - name: ContainerInstanceCount
        statistics:
        - Average
        period: 60
        length: 300
```

Is there something I'm missing? I tried to debug, but I saw no information about it.
