### ISSUE TITLE
Feature Request : redshift auto discovery via tags

### ISSUE THREAD

**Issue by michaeljoy** [ivx/yet-another-cloudwatch-exporter#129]
It would be highly useful for large redshift environments that change frequently to have dynamic tag based lookup similar to what you can currently do with the java based cloudwatch_exporter. It's tedious and obviously a non-start to have to manually define hundreds and or thousands of resources per region.

Example of useful checks that could be implemented...
```
  - type: redshift
    region: eu-west-1
    awsDimensions:
     - ClusterIdentifier
     - NodeId (may not be relevant for anything other than CPUUtilization)
    searchTags:
      - Key: environment
        Value: production
    metrics:
      - name: CPUUtilization
        statistics:
        - Average
        period: 600
        length: 600
      - name: PercentageDiskSpaceUsed
        statistics:
        - Maximum
        period: 600
        length: 600
      - name: QueriesCompletedPerSecond
        statistics:
        - Maximum
        period: 600
        length: 600
      - name: QueryDuration
        statistics:
        - Maximum
        period: 600
        length: 600
```
