### ISSUE TITLE
Can only see aws_ec2_info with tags and no actual metrics.

### ISSUE THREAD

**Issue by aleksei-klopkov-epam** [ivx/yet-another-cloudwatch-exporter#143]
I can only see aws_ec2_info with tags when query for metrics, no actual metrics is there. When i use aws cli i can get those metrics no problem. I have all IAM Permissions set up, the only difference is that we have "aws:SecureTransport": "true" condition. Could it be that yace does not support ssl connections?
here is my test config
```discovery:
  exportedTagsOnMetrics:
    ec2:
      - 'Name'
  jobs:
  - region: 'us-east-1'
    type: 'ec2'
    searchTags:
      - Key: 'Project'
        Value: 'preprod.*'
    awsDimensions:
     - 'InstanceId'
    metrics:
      - name: 'CPUCreditBalance'
        statistics:
        - 'Average'
        period: 300
        length: 300
        nilToZero: true
```

**Comment by aleksei-klopkov-epam** [comment]
All working normally on version 0.13.7

**Comment by daviddetorres** [comment]
I have a config working like this (the only visible difference is the awDimensions field. In EC2 it already selects the InstanceId from the resources, so no need to add it. 
```
discovery:
  jobs:
  - region: XXXX
    type: ec2
    enableMetricData: true
    metrics: 
      - name: CPUUtilization
        statistics:
        - Average
        period: 60
        length: 300
      - name: DiskReadOps
        statistics:
        - Average
        period: 60
        length: 300
      - name: DiskWriteOps
        statistics:
        - Average
        period: 60
        length: 300
```
