### ISSUE TITLE
 Only RequestCount metric was showed by YACE for Application ELB 

### ISSUE THREAD

**Issue by datton94** [ivx/yet-another-cloudwatch-exporter#146]
Hi, This is my configuration 

```
discovery:
  jobs:
  - type: alb
    roleArn: arn:aws:iam::xxxxxxx 
    region: eu-west-1 
    awsDimensions:
     - LoadBalancer
    metrics:
          - name: ActiveConnectionCount
            statistics:
            - Sum
            period: 60
            length: 600
          - name: HTTPCode_ELB_5XX_Count
            statistics:
            - Sum
            period: 60
            length: 300
          - name: HTTPCode_ELB_4XX_Count
            statistics:
            - Sum
            period: 60
            length: 300
          - name: HTTPCode_ELB_3XX_Count
            statistics:
            - Sum
            period: 60
            length: 300
          - name: RejectedConnectionCount
            statistics:
            - Sum
            period: 60
            length: 300
          - name: RequestCount
            statistics:
            - Sum
            period: 60
            length: 300
```

I run YACE on local, by docker. When I access to http://localhost:5000/metrics I only got the RequestCount metrics at all.
My roleArn is full admin permission, so I don't think permission is the root cause. 

Did I do anything wrong?

**Comment by icy** [comment]
@datton94 Please also have a look https://github.com/ivx/yet-another-cloudwatch-exporter#options if that helps

**Comment by daviddetorres** [comment]
Hi, 
No need to use the awsDimensions: LoadBalancer, due to it is automatically detected.
 
I share a config file that is working with all the metrics for ALB:
```
discovery:
  jobs:
  - region: XXXX
    type: alb
    enableMetricData: true
    metrics: 
      - name: ActiveConnectionCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ClientTLSNegotiationErrorCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ConsumedLCUs
        statistics:
        - Sum
        period: 300
        length: 3600
      
      - name: HTTP_Fixed_Response_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTP_Redirect_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTP_Redirect_Url_Limit_Exceeded_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_3XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_4XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_5XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_500_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_502_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_503_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_504_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: IPv6ProcessedBytes
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: IPv6RequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: NewConnectionCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ProcessedBytes
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: RejectedConnectionCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: RequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: RuleEvaluations
        statistics:
        - Sum
        period: 300
        length: 3600
      
      - name: LambdaTargetProcessedBytes
        statistics:
        - Sum
        period: 300
        length: 3600

      - name: ELBAuthError
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthFailure
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthLatency
        statistics:
        - Average
        period: 300
        length: 3600
      - name: ELBAuthRefreshTokenSuccess
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthSuccess
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthUserClaimsSizeExceeded
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
  - region: us-east-1
    type: alb
    enableMetricData: true
    awsDimensions:
      - AvailabilityZone
    metrics: 
      - name: DroppedInvalidHeaderRequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ForwardedInvalidHeaderRequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
  - region: us-east-1
    type: alb
    enableMetricData: true
    awsDimensions: 
      - TargetGroup
    metrics: 
      - name: HealthyHostCount
        statistics:
        - Average
        period: 300
        length: 3600
      - name: HTTPCode_Target_2XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_Target_3XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_Target_4XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_Target_5XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: NonStickyRequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: RequestCountPerTarget
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: TargetConnectionErrorCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: TargetResponseTime
        statistics:
        - p95
        period: 300
        length: 3600
      - name: TargetTLSNegotiationErrorCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: UnHealthyHostCount
        statistics:
        - Average
        period: 300
        length: 3600
      - name: LambdaInternalError
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: LambdaUserError
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
```
