### ISSUE TITLE
ecs and ecs-svc conflicting metric names

### ISSUE THREAD

**Issue by neshmi** [ivx/yet-another-cloudwatch-exporter#148]
I am trying to scrape both the ECS cluster metrics as well as the ECS service metrics. Autodiscovery doesn't seem to be working, although static configs do allow me to setup those metrics. However, I can't do both cluster level and service level metrics, as it panics when it tries to register this with prometheus (I'm guessing because of the added dimension?)

```
panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "aws_ecs_cpuutilization_average", help: "Help is not implemented yet.", constLabels: {dimension_ClusterName="<CLUSTER>",dimension_ServiceName="<SERVICE>",name="<NAME>",region="us-east-1"}, variableLabels: []}
```

I'm wondering if it would be possible to simply overwrite the fqName? So, for ECS level metrics, it would remain the same, but insert in _svc_ for the service level metrics so we don't get this clash?

aws_ecs_cpuutilization_average and aws_ecs_svc_cpuutilization_average ?

I think that it is just getting set as aws_ecs beccause of the namespacing? Another option, perhaps, would be to have the ability to overwrite the metric name in the yaml config? 

Also, perhaps I'm missing here too! Entirely possible! :)

Thanks!

Here are the static configs that will produce the conflict, partially redacted:

```
  - namespace: AWS/ECS
    region: us-east-1
    name: <NAME>
    dimensions:
      - name: ClusterName
        value: <CLUSTER>
    metrics:
      - name: CPUUtilization
        statistics: [Average]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
      - name: CPUReservation
        statistics: [Average]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
      - name: MemoryUtilization
        statistics: [Average]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
      - name: MemoryReservation
        statistics: [Average]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
  - namespace: AWS/ECS
    region: us-east-1
    name: <NAME>
    dimensions:
      - name: ClusterName
        value: <CLUSTER>
      - name: ServiceName
        value: <SERVICE>
    metrics:
      - name: CPUUtilization
        statistics: [Average]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
      - name: MemoryUtilization
        statistics: [Average]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
```

And as far as autodiscovery, this is what I tried:
```
- type: ecs-svc
    region: us-east-1
    awsDimensions:
      - ClusterName
      - ServiceName
    metrics:
      - name: CPUUtilization
        statistics: [Average]
        period: 600
        length: 600
      - name: MemoryUtilization
        statistics: [Average]
        period: 600
        length: 600
```

**Comment by thomaspeitz** [comment]
Could you try out on newest version, as there were some ecs changes lately. If not i would spend some time debugging this with you.

**Comment by thomaspeitz** [comment]
@neshmi - Forgot to tag you.

**Comment by sweepkim** [comment]
Hi all, 
I have similar issue using ecs-svc. the metric result is different depends on release version.

This is my config file.
```
- type: ecs-svc
    region: us-east-1
    enableMetricData: true
    roleArn: arn:aws:iam::XXXXXXXX:role/test
    awsDimensions:
    - ServiceName
    - ClusterName
    metrics:
    - name: CPUUtilization
      statistics: [Average]
      period: 300
      length: 3000
      nilToZero: true
    - name: MemoryUtilization
      statistics: [Average]
      period: 300
      length: 3000
      nilToZero: true

  - type: ecs-svc
    region: us-east-1
    enableMetricData: true
    roleArn: arn:aws:iam::XXXXXXXX:role/test
    awsDimensions:
    - ClusterName
    metrics:
    - name: CPUReservation
      statistics: [Average]
      period: 300
      length: 3000
      nilToZero: true
    - name: MemoryReservation
      statistics: [Average]
      period: 300
      length: 3000
      nilToZero: true
```

**0.14.0**
It shows 4 metrics as I wish.
aws_ecs_svc_cpureservation_average{dimension_ClusterName="aaa", ...}
aws_ecs_svc_cpuutilization_average{dimension_ClusterName="aaa",dimension_ServiceName="bbb", ...}
aws_ecs_svc_memory_reservation_average{dimension_ClusterName="aaa",...}
aws_ecs_svc_memory_utilization_average{dimension_ClusterName="aaa", dimension_ServiceName="bbb", ...}

**0.15.0**
It shows only aws_ecs_svc_info{} and no more metrics.

**0.16.0~**
No aws_ecs_svc_XXX metrics.

I hope this is helpful for debugging.

**Comment by lmasaya** [comment]
I'm using the `v0.18.0-alpha` version of the exporter and trying the following configuration:
```
- type: ecs-svc
    regions: [${regions}]
    roleArn: arn:aws:iam::${aws_account}:role/prometheus-metrics-collection-role
    metrics:
      - name: CPUUtilization
        length: 300
		statistics: [Average]
        period: 30
      - name: MemoryUtilization
        length: 300
		statistics: [Average]
        period: 30
```
This is in a template that I checked that it renders correctly.
Not getting any metrics back besides the `aws_ecs_svc_info`.
Any suggestions?
