### ISSUE TITLE
Metrics missing with version 0.16.0

### ISSUE THREAD

**Issue by vaishalisutaria** [ivx/yet-another-cloudwatch-exporter#151]
We would like to update YACE to 0.16.0. While testing with this update, we noticed that we are not getting following metric which we used to with version 0.14.7.
aws_alb_info

We are also not getting a static metric with namespace `OurCustomMetric`.
Our configuration looks like below:
```
discovery:
  jobs:
  - region: us-west-2
    type: alb
    metrics:
    - name: HealthyHostCount
      statistics: [Average]
      period: 60
      length: 600
      delay: 600
  - type: s3
    region: us-west-2
    metrics:
    - name: BytesUploaded
      statistics: [Sum]
      period: 60
      length: 600
      delay: 600
      additionalDimensions:
      - name: FilterId
        value: EntireBucket
      nilToZero: true
  - type: emr
    region: us-west-2
    metrics:
    - name: AppsRunning
      statistics: [Average]
      period: 60
      length: 600
      delay: 600
static:
  - namespace: OurCustomMetric
    name: Custom-us-west-2
    region: us-west-2
    dimensions:
    - name: Environment
      value: prod
    customTags:
    - Key: account_id
      Value: "12345"
    - Key: environment
      Value: prod
    metrics:
    - name: JobSucceeded
      statistics:
      - 'Sum'
      period: 60
      length: 600
      delay: 600
      nilToZero: true
```
With version 0.16.0, aws_alb_* and aws_alb_tg_* metrics are missing and the aws_emr_* and aws_s3_* metrics seem to be returning only one or two metrics (e.g. aws_s3_info/aws_emr_info)

Custom metric that we get with version 0.14.7 (e.g. TYPE aws_our_custom_metric_job_succeeded_sum) is missing with version 0.16.0

Here is the resultant metrics information with version 0.14.7
```
# HELP aws_alb_info Help is not implemented yet.
# TYPE aws_alb_info gauge
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:12345:loadbalancer/app/abc-i-Porta-Z9D8RUC8TK1K/7c01cdaf0248953e",tag_Category="NETWORK",REDACTED...} 0
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:12345:loadbalancer/abc-stage-BackendP-UP9GY9WZGXBE",tag_Category="APPLICATION",REDACTED...} 0
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:12345:targetgroup/abc-t-Porta-1OPUS4I9RPN2L/af3443a1d2a328dc",tag_Category="NETWORK",REDACTED...} 0
<...more metrics>
# HELP aws_alb_tg_healthy_host_count_average Help is not implemented yet.
# TYPE aws_alb_tg_healthy_host_count_average gauge
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-i-Porta-Z9D8RUC8TK1K/7c01cdaf0248953e",dimension_TargetGroup="targetgroup/REDACTED..} 1
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-i-Porta-Z9D8RUC8TK1K/7c01cdaf0248953e",dimension_TargetGroup="targetgroup/REDACTED...} 1
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Porta-EJM0LMM26AG8/e31df8a9f931e41f",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Rever-13V2WZZEMU7ZO/986210d501a90433",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Rever-13V2WZZEMU7ZO/986210d501a90433",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Rever-1S4S93J86AYHQ/9275d53c70db07b8",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-s-Rever-TQBYMSWS2LGW/92e719d8ec2c4bf7",dimension_TargetGroup="targetgroup/REDACTED...} 2
<...more metrics>
# HELP aws_emr_info Help is not implemented yet.
# TYPE aws_emr_info gauge
aws_emr_info{name="arn:aws:elasticmapreduce:us-west-2:12345:cluster,...} 0
aws_emr_info{name="arn:aws:elasticmapreduce:us-west-2:12345:cluster,...} 0
<...more metrics>
# HELP aws_our_custom_metric_job_succeeded_sum Help is not implemented yet.
# TYPE aws_our_custom_metric_job_succeeded_sum gauge
aws_our_custom_metric_job_succeeded_sum{custom_tag_account_id="12345",custom_tag_environment="prod",dimension_Environment="prod",name="Custom-us-west-2",region="us-west-2"} 0
# HELP aws_s3_bytes_uploaded_sum Help is not implemented yet.
# TYPE aws_s3_bytes_uploaded_sum gauge
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
<...more metrics>
# HELP aws_s3_info Help is not implemented yet.
# TYPE aws_s3_info gauge
aws_s3_info{name="REDACTED",...} 0
aws_s3_info{name="REDACTED",...} 0
<...more metrics>
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 139
```
And below is the resultant metrics information with version 0.16.0
```
# HELP aws_emr_info Help is not implemented yet.
# TYPE aws_emr_info gauge
aws_emr_info{name="arn:aws:elasticmapreduce:us-west-2:12345:cluster/j-3C8O7TIJIVPLT",...} 0
# HELP aws_s3_bytes_uploaded_sum Help is not implemented yet.
# TYPE aws_s3_bytes_uploaded_sum gauge
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket"...region="us-west-2"} 0
# HELP aws_s3_info Help is not implemented yet.
# TYPE aws_s3_info gauge
aws_s3_info{name="REDACTED",...} 0
# HELP yace_cloudwatch_autoscalingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_autoscalingapi_requests_total counter
yace_cloudwatch_autoscalingapi_requests_total 0
# HELP yace_cloudwatch_getmetricdata_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricdata_requests_total counter
yace_cloudwatch_getmetricdata_requests_total 2
# HELP yace_cloudwatch_getmetricstatistics_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricstatistics_requests_total counter
yace_cloudwatch_getmetricstatistics_requests_total 1
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 6
# HELP yace_cloudwatch_resourcegrouptaggingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_resourcegrouptaggingapi_requests_total counter
yace_cloudwatch_resourcegrouptaggingapi_requests_total 4

```

Please help us figure out what is causing these metrics to be missing.
Thank you
