### ISSUE TITLE
VPN metrics by TunnelIpAddress dimension

### ISSUE THREAD

**Issue by aperigault** [ivx/yet-another-cloudwatch-exporter#158]
Hi,

I don't know if it's realy an issue or a configuration mistake but I don't understand why.
This configuration works:
```
      - type: vpn
        region: eu-west-1
        length: 300
        metrics:
          - name: TunnelState
            statistics:
              - Minimum
            period: 120
          - name: TunnelDataIn
            statistics:
              - Minimum
            period: 120
          - name: TunnelDataOut
            statistics:
              - Minimum
            period: 120
```
But not this one with optional `awsDimensions`:
```
      - type: vpn
        region: eu-west-1
        awsDimensions:
         - TunnelIpAddress
        length: 300
        metrics:
          - name: TunnelState
            statistics:
              - Minimum
            period: 120
          - name: TunnelDataIn
            statistics:
              - Minimum
            period: 120
          - name: TunnelDataOut
            statistics:
              - Minimum
            period: 120
```

This exporter seem's to be realy great. It's the last feature that I need to run in production.
