### ISSUE TITLE
[0.18.0-Alpha] region vs regions

### ISSUE THREAD

**Issue by karlesnine** [ivx/yet-another-cloudwatch-exporter#187]
Very strange behavior with version 0.18.0-alpha in case of error on the auto-discovery job "regions" if you write it "region" without s

I experimented with the following configuration file

```
discovery:
  exportedTagsOnMetrics:
    elb:
      - Project
      - Name
  jobs:
  - type: elb
    region:
      - eu-west-1
    searchTags:
      - Key: Project
        Value: .*
    metrics:
      - name: HealthyHostCount
        statistics:
        - Minimum
        period: 600
        length: 600
```

- Yace start without problem
- No error message event in debug mode
- Yace responds on 5000:/metrics but `yace_cloudwatch_requests_total` remains at zero
- The debug mode only displays requests about consult metrics
- No log activity about request to cloudwatch
- I have been watching network activity with tcpdump and I have not seen any calls to cloudwatch
- I try many possibility with `-decoupled-scraping` and `-scraping-interval=60`
- I'm waiting 5 minutes for each test

Yace is stable, does not return any error message, but does not query cloudwatch. 
It's very vicious
