### ISSUE TITLE
Returned metrics are inconsistent and average crashes the service

### ISSUE THREAD

**Issue by cullenmcdermott** [ivx/yet-another-cloudwatch-exporter#20]
I have the following config:
```
discovery:
  - region: us-west-2
    type: 'ec2'
    searchTags:
      - Key: 'aws:elasticmapreduce:instance-group-role'
        Value: 'MASTER'
    metrics:
      - name: CPUUtilization
        statistics:
        - 'Average'
        period: 300
        length: 60
      - name: StatusCheckFailed
        statistics:
        - 'Maximum'
        period: 300
        length: 60
```
My goal is to return all my EMR master nodes and get their CPU Usage as well as if they've had a status check fail.

Whenever I do this a couple of unexpected things happen:
1) YACE crashes with the following message
```
2018/10/22 17:27:38 Parse config..
2018/10/22 17:27:38 Startup completed
2018/10/22 17:27:41 Not implemented statisticsAverage
```
2) When I change the CPUUtilization statistic to Maximum it doesn't crash but sometimes it only returns one or two instances and sometimes it returns none(instead of 11 instances like I expect).

I've tested with both 0.6.1 and 0.7.0-alpha
