### ISSUE TITLE
Bug : Kinesis Enhanced Shard-Level metrics not showing on a per shard basis

### ISSUE THREAD

**Issue by Bachib** [ivx/yet-another-cloudwatch-exporter#216]
After enabling [Enhanced Shard-Level metrics](https://docs.aws.amazon.com/streams/latest/dev/monitoring-with-cloudwatch.html) for Kinesis, all I see in Prometheus is :

`aws_kinesis_incoming_records_sum{dimension_StreamName="test-stream",instance="xx.xx.xx.xx:xx",job="cloudwatch-exporter-kinesis",name="arn:aws:kinesis:us-west-1:XXXXXXXX:stream/test-stream",namespace="exporters",pod="cloudwatch-exporter-kinesis-xxxxxxxx",region="us-west-1"}`

I would be expecting the dimension `ShardId` to be added as a label to the metric.

The YACE is already collecting the ShardId dimension in its ListMetricsResponse (seen from a `--debug` enabled exporter).

```
      <member>
        <Namespace>AWS/Kinesis</Namespace>
        <MetricName>IncomingRecords</MetricName>
        <Dimensions>
          <member>
            <Name>ShardId</Name>                       <------
            <Value>shardId-000000000003</Value>       
          </member>
          <member>
            <Name>StreamName</Name>
            <Value>test-stream</Value>
          </member>
        </Dimensions>
      </member>
```  

Here is my config.
```
discovery:
  jobs:
  - type: kinesis
    enableMetricData: true
    regions:
      - us-west-1
    roleArn: arn:aws:iam::XXXXXXXXXXXX:role/CwRead
    metrics:
      - name: IncomingRecords
        statistics:
        - Sum
        period: 60
        length: 300
      - name: IncomingBytes
        statistics:
        - Sum
        period: 60
        length: 300
```

I also tried adding awsDimensions to the config, but when I do, I am not receiving any data in Prometheus :

```
    awsDimensions:
      - ShardId
      - StreamName
```

I am doing all this because AWS does not expose a metric showing the amount of shards there is in a Kinesis Stream. The amount of open shard is useful to determine if your Stream's shard count is sufficient, to know if the amount of shard should be scaled or downscaled. To my knowledge, the only way to get the shard count would be via the Enhanced Shard-Level Metrics. If there is another easier way to do this, I would also be happy. Maybe adding the open shard count to the metric `aws_kinesis_info` ?

**Comment by ishantkumar** [comment]
@Bachib - I am using below config and its working for me .

```
jobs:
  - type: kinesis
    regions:
     - ap-northeast-1
     - us-east-1
     - eu-west-1
    awsDimensions:
     - ShardId
    metrics:
      - name: IteratorAgeMilliseconds
        statistics:
        - Average
        period: 600
        length: 600
      - name: IncomingRecords
        statistics:
        - Average
        period: 600
        length: 600
```
