### ISSUE TITLE
YACE and Trusted Advisor metrics

### ISSUE THREAD

**Issue by vlinden-cs** [ivx/yet-another-cloudwatch-exporter#218]
Hi,

Can YACE be used to pull TrustedAdvisor metrics from CloudWatch?
It seems like the trusted advisor metrics have another level between the namespace and the metric itself. 
IF it's possible, I would love an example that pull the autoscaling group limit usage (how many ASG are used out of the allowed limit on the account)

**Comment by thomaspeitz** [comment]
Hey @vlinden-cs,

you should be able to pull those metrics through `static` feature of yace. You can find out the values you need through cloudwatch interface:

Example of such metrics:

![image](https://user-images.githubusercontent.com/8327755/89031778-73ee2080-d333-11ea-84b3-31db70f157ba.png)

Dimensions are in my example the ones in the header of the table: Region, ServiceLimit, ServiceName, Metric Name. For example:
```
    dimensions:
     - name: Region
       value: ap-east-1
     - name: ServiceLimit
        value: "Auto Scaling groups"
....
```

Namespace should be: `AWS/TrustedAdvisor`

If you get it working, please add your working config in the issue for others :)

In the meantime i am closing it here.

**Comment by mvadu** [comment]
As @thomaspeitz  mentioned adding it for the benefit of others
```yaml
apiVersion: v1alpha1
static:
  - namespace: AWS/TrustedAdvisor
    name: advisor
    regions:
      - us-east-1
    metrics:
      - name: ServiceLimitUsage
        statistics:
        - Sum
      - name: RedChecks
        statistics:
        - Sum
      - name: YellowChecks
        statistics:
        - Sum
```
