### ISSUE TITLE
Bug: config file complains about missing period in metrics, while the period has been defined at job level

### ISSUE THREAD

**Issue by jylitalo** [ivx/yet-another-cloudwatch-exporter#219]
Version: 0.19-alpha

Config file starts as:
```
---
discovery:
  jobs:
    - type: alb
      period: 600
      length: 600
      regions:
        - eu-west-1
      roleArns:
...
      metrics:
        - name: HealthyHostCount
          statistics:
            - Average
            - Maximum
            - Minimum
... 
```

and it complains in logs that:
> {"level":"fatal","msg":"Couldn't read s3://yle-yace-test/config.yml: Metric [0] in Discovery job [0]: Period value should be a positive integer","time":"2020-07-31T07:20:38Z"}

If we already define `period` in `job` level, config validation should not complain that we haven't redefined it in `metrics`.
