### ISSUE TITLE
Use GetMetricData instead of GetMetricStatistics?

### ISSUE THREAD

**Issue by nhinds** [ivx/yet-another-cloudwatch-exporter#23]
Currently yace with a relatively simple configuration makes 300 requests to cloudwatch for my 20 loadbalancers, retrieving each metric for each loadbalancer individually.

Since AWS supports bulk metric retrieval with its `GetMetricData` API, could this be used instead of `GetMetricStatistics`? It would reduce the number of API calls from 300 down to about 3 (there is a limit of 100 metrics per request)

My simple configuration:
```
discovery:
  - type: elb
    region: us-west-2
    searchTags:
      - Key: Service
        Value: abc
    metrics:
      - name: BackendConnectionErrors
        statistics: [Sum]
        period: 60
        length: 600
      - name: HealthyHostCount
        statistics: [Average]
        period: 60
        length: 600
      - name: HTTPCode_Backend_2XX
        statistics: [Sum]
        period: 60
        length: 600
      - name: HTTPCode_Backend_3XX
        statistics: [Sum]
        period: 60
        length: 600
      - name: HTTPCode_Backend_4XX
        statistics: [Sum]
        period: 60
        length: 600
      - name: HTTPCode_Backend_5XX
        statistics: [Sum]
        period: 60
        length: 600
      - name: HTTPCode_ELB_4XX
        statistics: [Sum]
        period: 60
        length: 600
      - name: HTTPCode_ELB_5XX
        statistics: [Sum]
        period: 60
        length: 600
      - name: Latency
        statistics: [Average]
        period: 60
        length: 600
      - name: RequestCount
        statistics: [Sum]
        period: 60
        length: 600
      - name: SpilloverCount
        statistics: [Sum]
        period: 60
        length: 600
      - name: SurgeQueueLength
        statistics: [Maximum, Sum]
        period: 60
        length: 600
      - name: UnHealthyHostCount
        statistics: [Average]
        period: 60
        length: 600
  - type: alb
    region: us-west-2
    searchTags:
      - Key: Service
        Value: abc
    metrics:
      - name: ActiveConnectionCount
        statistics: [Sum]
        period: 60
        length: 600
      - name: UnHealthyHostCount
        statistics: [Average]
        period: 60
        length: 600
```
