### ISSUE TITLE
Different values of metrics in AWS Cloudwatch and YACE for some of ALBs not ALL

### ISSUE THREAD

**Issue by shubhamc183** [ivx/yet-another-cloudwatch-exporter#242]
I am trying to scrape AWS Application ELB with this config file with `--scraping-interval=60` in decoupled scraping mode.

```
discovery:
  jobs:
  - type: alb
    regions:
      - us-east-1
    metrics:
      - name: RequestCount
        statistics: [Sum]
        period: 60
        length: 60
        delay: 120
        nilToZero: true
        addCloudwatchTimestamp: true
```
The period is 60 as I want to sum on every minute, the length is 60 as I want to start just go 1 minute back, with the delay of 2 mins as ALB takes 2 mins to converge the metrics completely.

So, at 2:00 PM YACE will be asking AWS-CW to the aggregate `SUM` of `RequestCount` with 1 min period of data b/w 1:57 to 1:58 PM, right? Please let me know if I understood this correctly.

I am observing some different values of metrics in AWS Cloudwatch and YACE. In the below picture only some values of the YACE match with the Cloudwatch data.

![yace-cloudwatch](https://user-images.githubusercontent.com/15362871/91601941-1b3c9280-e988-11ea-8f43-42fefb9ae1fd.png)

**BUT FOR SOME ALBs THE DATA IS CORRECT**

I also tried with `length: 600` instead of 60 with the same `--scraping-interval=60` in decoupled scraping mode and the values were still different

![yace-cloudwatch-length600](https://user-images.githubusercontent.com/15362871/91604426-3e694100-e98c-11ea-9aa8-31b77b36a3d6.png)

**BUT FOR SOME ALBs THE DATA IS CORRECT**

Even with  `--scraping-interval=300` I am getting different values. The reason why I started with `--scraping-interval=60` was because I want to generate alerts with SLO error burn rate, I will use `offset=delay`.

**I have 71 ALBs but aws_alb_info is 54 whereas aws_alb_request_count_sum is 31 time-series.**

**Extra Question**: If I keep `period:60`, `length:600`, `delay:120`(default) then I'll get 10 metrics aggregated at 1min interval but Prometheus will save only the last one so what's the use of remaining 9 metrics. Prometheus is append-only DB. Does it have an impact on price if the number of ALBs are 100s+?
