### ISSUE TITLE
403 Error when fetching tagged API Gateway resources

### ISSUE THREAD

**Issue by Botono** [ivx/yet-another-cloudwatch-exporter#262]
I have granted YACE all the required permissions according to the README. However, this error is being logged:

```json
{"level":"error","msg":"tagsInterface.get: apigateway: getTaggedApiGateway: AccessDeniedException: \n\tstatus code: 403, request id: 2628044d-c03b-42a0-850a-947b2ff42a59","time":"2020-10-17T21:51:01Z"}
{"level":"info","msg":"Couldn't describe resources for region us-west-2: AccessDeniedException: \n\tstatus code: 403, request id: 74bd4b35-5904-485a-9e04-afbe822c2324\n","time":"2020-10-17T22:02:01Z"}
```
The role has the `CloudWatchReadOnlyAccess` managed policy, which has the following permissions:

```json
      {
            "Action": [
                "autoscaling:Describe*",
                "cloudwatch:Describe*",
                "cloudwatch:Get*",
                "cloudwatch:List*",
                "logs:Get*",
                "logs:List*",
                "logs:StartQuery",
                "logs:StopQuery",
                "logs:Describe*",
                "logs:TestMetricFilter",
                "logs:FilterLogEvents",
                "sns:Get*",
                "sns:List*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
```
As well as an additional custom policy with these permissions:

```json
        {
            "Effect": "Allow",
            "Action": [
                "tag:getResources",
                "ec2:DescribeTransitGateway*",
                "ec2:DescribeTags",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances"
            ],
            "Resource": "*"
        }
```
Here is the API Gateway portion of my config:

```yaml
discovery:
  jobs:
  - type: apigateway
    regions:
      - us-west-2
    period: 60
    length: 300
    delay: 300
    searchTags:
      - Key: Environment
        Value: production
    awsDimensions:
      - ApiName
    metrics:
      - name: IntegrationLatency
        statistics: [Maximum, Minimum, Sum, Average]
        nilToZero: true
      - name: Latency
        statistics: [Maximum, Minimum, Sum, Average]
        nilToZero: true
      - name: 4XXError
        statistics: [Maximum, Minimum, Sum, Average]
        nilToZero: true
      - name: 5XXError
        statistics: [Maximum, Minimum, Sum, Average]
        nilToZero: true
      - name: Count
        statistics: [Maximum, Minimum, Sum, Average]
        nilToZero: true
```
