### ISSUE TITLE
Missing DataPoints - Causing Gaps on Grafana

### ISSUE THREAD

**Issue by singhjagmohan1000** [ivx/yet-another-cloudwatch-exporter#264]
I am getting issues with metrics for All AWS Namespaces. I can see gap of 1 min interval appearing in Grafana at every 40 to 45 minutes. Config File used
```
discovery:
  jobs:
  - type: dynamodb
    regions:
     - us-west-2
    period: 300
    length: 600
    delay: 600
    addCloudwatchTimestamp: true
    nilToZero: true
    metrics:
    - name: ConditionalCheckFailedRequests
      statistics: ['Average','Minimum','Maximum','Sum']
    - name: ConsumedReadCapacityUnits
      statistics: ['Average','Minimum','Maximum','Sum',]
    - name: ConsumedWriteCapacityUnits
      statistics: ['Average','Minimum','Maximum','Sum']
    - name: ProvisionedWriteCapacityUnits
      statistics: ['Average','Minimum','Maximum']
    - name: ReadThrottleEvents
      statistics: ['Sum']
    - name: SuccessfulRequestLatency
      statistics: ['Average','Minimum','Maximum','Sum']
    - name: SystemErrors
      statistics: ['Sum']
    - name: ThrottledRequests
      statistics: ['Sum']
    - name: UserErrors
      statistics: ['Sum']
    - name: WriteThrottleEvents
      statistics: ['Sum']
```

![image](https://user-images.githubusercontent.com/15527219/96362805-c219f100-10e4-11eb-88d2-70b69edfcbeb.png)

Debug Log: Output has been filtered to get Timestamp Only.
```
Timestamps: [2020-10-18 01:41:00 +0000 UTC,2020-10-18 01:36:00 +0000 UTC]
Timestamps: [2020-10-18 01:46:00 +0000 UTC,2020-10-18 01:41:00 +0000 UTC]
*******One min Gap in Timestamp below, It relates to Gap in Grafana******
Timestamps: [2020-10-18 01:52:00 +0000 UTC,2020-10-18 01:47:00 +0000 UTC]
Timestamps: [2020-10-18 01:57:00 +0000 UTC,2020-10-18 01:52:00 +0000 UTC]
Timestamps: [2020-10-18 02:02:00 +0000 UTC,2020-10-18 01:57:00 +0000 UTC]
Timestamps: [2020-10-18 02:07:00 +0000 UTC,2020-10-18 02:02:00 +0000 UTC]
Timestamps: [2020-10-18 02:12:00 +0000 UTC,2020-10-18 02:07:00 +0000 UTC]
Timestamps: [2020-10-18 02:17:00 +0000 UTC,2020-10-18 02:12:00 +0000 UTC]
Timestamps: [2020-10-18 02:22:00 +0000 UTC,2020-10-18 02:17:00 +0000 UTC]
Timestamps: [2020-10-18 02:27:00 +0000 UTC,2020-10-18 02:22:00 +0000 UTC]
Timestamps: [2020-10-18 02:32:00 +0000 UTC,2020-10-18 02:27:00 +0000 UTC]
Timestamps: [2020-10-18 02:37:00 +0000 UTC,2020-10-18 02:32:00 +0000 UTC]
Timestamps: [2020-10-18 02:42:00 +0000 UTC,2020-10-18 02:37:00 +0000 UTC]
******One min Gap in Timestamp below, It relates to Gap in Grafana*******
Timestamps: [2020-10-18 02:48:00 +0000 UTC,2020-10-18 02:43:00 +0000 UTC]
Timestamps: [2020-10-18 02:53:00 +0000 UTC,2020-10-18 02:48:00 +0000 UTC]
```

This look like a performance Issue with the code, where it cause some delay while processing the data. As StartTime and EndTime are calculated by length with function `time.Now()` it cause extra 1m gap at certain intervals.
