### ISSUE TITLE
Feature: Avoid selecting last timestamp, offer all timestamps via /metrics

### ISSUE THREAD

**Issue by friedrich-at-adobe** [ivx/yet-another-cloudwatch-exporter#268]
I wonder if it would be possible to offer all timestamps received via /metrics.
This would avoid the need to compute averages like shown on
https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.23.0-alpha/aws_cloudwatch.go#L687-L699
providing more accurate data

Example configuration
```
discovery:
  jobs:
  - delay: 600
    metrics:
    - addCloudwatchTimestamp: true
      name: ConsumedReadCapacityUnits
      period: 60
      length: 300
      statistics:
      - Average
    regions:
    - us-east-1
    type: dynamodb
```

Ideally this should produce something like

```
# HELP aws_dynamo_db_consumed_read_capacity_units_average Help is not implemented yet.
# TYPE aws_dynamo_db_consumed_read_capacity_units_average gauge
aws_dynamodb_consumed_read_capacity_units_average{dimension_TableName="sometable",name="somename",region="us-east-1"} 1 1603353960000
aws_dynamodb_consumed_read_capacity_units_average{dimension_TableName="sometable",name="somename",region="us-east-1"} 2 1603354020000
aws_dynamodb_consumed_read_capacity_units_average{dimension_TableName="sometable",name="somename",region="us-east-1"} 3 1603354080000
aws_dynamodb_consumed_read_capacity_units_average{dimension_TableName="sometable",name="somename",region="us-east-1"} 4 1603354120000
aws_dynamodb_consumed_read_capacity_units_average{dimension_TableName="sometable",name="somename",region="us-east-1"} 5 1603354180000
```

Which prometheus is able to ingest because the timestamps are sorted
![Screenshot from 2020-10-22 10-26-15](https://user-images.githubusercontent.com/35104428/96845614-29230700-1451-11eb-8016-42d942ba1454.png)
