### ISSUE TITLE
ValidationError: You cannot describe more than '20' target groups at a time

### ISSUE THREAD

**Issue by abhishek-annigeri** [ivx/yet-another-cloudwatch-exporter#278]
I see the below error message in the logs, can someone help me understand what I am doing here. 
Thanks in advance. 

Error Message: `"level":"error","msg":"Error describeTargetGroups for alb , err: ValidationError: You cannot describe more than '20' target groups at a time\n\tstatus code: 400`

Here is my config file: 

> 
```
discovery:
  jobs:
  - type: alb
    regions:
      - us-east-1
    metrics:
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 600
        length: 600
```
