### ISSUE TITLE
Discovery is not discovering all items

### ISSUE THREAD

**Issue by vladkolodny** [ivx/yet-another-cloudwatch-exporter#283]
Hi,

I am facing strange issue - Discovery is not discovering all objects.
As example: I have 7 Application LoadBalancers in us-west-2. Discovery is discovering only 6.
But using "static:" I can scrap the "missing ALB".
Same happens with target groups and S3.
PFB config.xml.
You can see that discovery doesn't discover the "app/anytime-lb/0857d5f984c93c7b" but it can be scrapped using static configuration.
Am I missing something ?

Thank you very much !

```
discovery:
  jobs:
  - type: alb
    regions:
      - us-west-2
    enableMetricData: true
    metrics:
      - name: HealthyHostCount
        statistics:
        - Sum
        period: 600
        length: 600
        nilToZero: true
      - name: NewConnectionCount
        statistics:
        - Sum
        period: 600
        length: 600
        nilToZero: true
static:
  - namespace: AWS/ApplicationELB
    name: RequestCount
    regions:
      - us-west-2
    dimensions:
      - name: LoadBalancer
        value: app/anytime-lb/0857d5f984c93c7b
    metrics:
      - name: NewConnectionCount
        statistics:
        - Sum
        period: 600
        length: 600

```

Output:

```
# HELP aws_alb_info Help is not implemented yet.
# TYPE aws_alb_info gauge
aws_alb_info 0
# HELP aws_alb_new_connection_count_sum Help is not implemented yet.
# TYPE aws_alb_new_connection_count_sum gauge
aws_alb_new_connection_count_sum{dimension_LoadBalancer="app/staging-decrypt-alb/1fff948c39446797",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:loadbalancer/app/staging-decrypt-alb/1fff948c39446797",region="us-west-2"} 0
aws_alb_new_connection_count_sum{dimension_LoadBalancer="app/staging-f5-alb/554ac6a40327cb72",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:loadbalancer/app/staging-f5-alb/554ac6a40327cb72",region="us-west-2"} 3
aws_alb_new_connection_count_sum{dimension_LoadBalancer="app/staging-rtbl-alb/6a808a07858cd0b3",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:loadbalancer/app/staging-rtbl-alb/6a808a07858cd0b3",region="us-west-2"} 0
aws_alb_new_connection_count_sum{dimension_LoadBalancer="app/staging-ws-rest-alb/8c8623adb71eda4f",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:loadbalancer/app/staging-ws-rest-alb/8c8623adb71eda4f",region="us-west-2"} 2428
aws_alb_new_connection_count_sum{dimension_LoadBalancer="app/staging-ws-secure-alb/d0771fbf377631e0",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:loadbalancer/app/staging-ws-secure-alb/d0771fbf377631e0",region="us-west-2"} 1986
aws_alb_new_connection_count_sum{dimension_LoadBalancer="app/staging-ws-soap-alb/4f6a67273d75fb48",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:loadbalancer/app/staging-ws-soap-alb/4f6a67273d75fb48",region="us-west-2"} 1270
# HELP aws_alb_tg_healthy_host_count_sum Help is not implemented yet.
# TYPE aws_alb_tg_healthy_host_count_sum gauge
aws_alb_tg_healthy_host_count_sum{dimension_LoadBalancer="app/staging-decrypt-alb/1fff948c39446797",dimension_TargetGroup="targetgroup/staging-decrypt-alb/854960b0b67cd6c5",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:targetgroup/staging-decrypt-alb/854960b0b67cd6c5",region="us-west-2"} 40
aws_alb_tg_healthy_host_count_sum{dimension_LoadBalancer="app/staging-rtbl-alb/6a808a07858cd0b3",dimension_TargetGroup="targetgroup/staging-rtbl-alb/c5a7025552588d71",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:targetgroup/staging-rtbl-alb/c5a7025552588d71",region="us-west-2"} 0
aws_alb_tg_healthy_host_count_sum{dimension_LoadBalancer="app/staging-ws-rest-alb/8c8623adb71eda4f",dimension_TargetGroup="targetgroup/staging-rest-alb/e7b30644234f902b",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:targetgroup/staging-rest-alb/e7b30644234f902b",region="us-west-2"} 90
aws_alb_tg_healthy_host_count_sum{dimension_LoadBalancer="app/staging-ws-secure-alb/d0771fbf377631e0",dimension_TargetGroup="targetgroup/staging-secure-alb/c3fa613a6182241f",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:targetgroup/staging-secure-alb/c3fa613a6182241f",region="us-west-2"} 38
aws_alb_tg_healthy_host_count_sum{dimension_LoadBalancer="app/staging-ws-soap-alb/4f6a67273d75fb48",dimension_TargetGroup="targetgroup/staging-soap-alb/d879ad9b995d1a9d",name="arn:aws:elasticloadbalancing:us-west-2:033551664545:targetgroup/staging-soap-alb/d879ad9b995d1a9d",region="us-west-2"} 40
# HELP aws_application_elb_new_connection_count_sum Help is not implemented yet.
# TYPE aws_application_elb_new_connection_count_sum gauge
aws_application_elb_new_connection_count_sum{dimension_LoadBalancer="app/anytime-lb/0857d5f984c93c7b",name="RequestCount",region="us-west-2"} 4
# HELP yace_cloudwatch_apigatewayapi_requests_total
# TYPE yace_cloudwatch_apigatewayapi_requests_total counter
yace_cloudwatch_apigatewayapi_requests_total 0
# HELP yace_cloudwatch_autoscalingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_autoscalingapi_requests_total counter
yace_cloudwatch_autoscalingapi_requests_total 0
# HELP yace_cloudwatch_getmetricdata_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricdata_requests_total counter
yace_cloudwatch_getmetricdata_requests_total 1
# HELP yace_cloudwatch_getmetricstatistics_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricstatistics_requests_total counter
yace_cloudwatch_getmetricstatistics_requests_total 1
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 4
# HELP yace_cloudwatch_resourcegrouptaggingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_resourcegrouptaggingapi_requests_total counter
yace_cloudwatch_resourcegrouptaggingapi_requests_total 1
```
