### ISSUE TITLE
Value of "HealthyHosCount" on ALB doesn't get updated in YACE even if cloudwatch value change

### ISSUE THREAD

**Issue by JnMik** [ivx/yet-another-cloudwatch-exporter#289]
So I am using YACE 0.24-alpha with the following config

```
    - type: alb
      length: 600
      regions:
        - ca-central-1
      enableMetricData: true
      searchTags:
        - Key: Environment
          Value: ${var.env}
      metrics:
        - name: HealthyHostCount
          statistics:
          - Maximum
          period: 600
        - name: UnHealthyHostCount
          statistics:
          - Maximum
          period: 600
```
If I start with a target group with an healthy container, and boot YACE, the value will be reported correctly (HealthyHostCount will be equal to 1 and UnHealthyHostCount will be equal to zero).

If I shutdown the container, I see UnHealthyHostCount raise to 1, but Healthy doesn't drop to zero, like it's stuck in some kind of cache. (The value does change into Cloudwatch).

Then after, if I boot the container that I'd just shutdown, UnHealthyHostCount stays stuck to 1.

It seems when a value reach 1, it never go back to zero. I suspected the "maximum" statistics to be the culprit, be even if I le the 600 period completely rotate, it never changes. I also tried with a smaller period and length with no success.

I'm not sure why I am doing wrong, any help appreciated ! 

Thanks
--jm
