### ISSUE TITLE
Autodiscovery job, not all ECS Fargate clusters discovered

### ISSUE THREAD

**Issue by pluvio-phile** [ivx/yet-another-cloudwatch-exporter#290]
Hi,
Using version 0.24.0-alpha. I have 2 Fargate clusters and when I use the configuration below, i get metrics only for one of the ECS fargate clusters.  am I missing something? Here is how the metric name space looks like in CW. For the `awsDimensions` property, I tried using just "ClusterName" but that did not work either.

Any help would be appreciated!

![image](https://user-images.githubusercontent.com/69119938/102281095-4bd71680-3efc-11eb-99d9-fae9a9305e73.png)

```
---
discovery:
  jobs:
  - type: ecs-containerinsights
    regions:
      - us-east-1
    roleArns:
      - "#####"
    enableMetricData: true
    awsDimensions:
      - ClusterName
      - ServiceName
    metrics:
      - name: CpuReserved
        statistics:
        - Average
        period: 60
        length: 300
        nilToZero: true
      - name: CpuUtilized
        statistics:
        - Average
        period: 60
        length: 300
        nilToZero: true
```
