### ISSUE TITLE
[Redshift] Auto discovery job not working

### ISSUE THREAD

**Issue by Markoj96** [ivx/yet-another-cloudwatch-exporter#296]
Hi guys, in the list of jobs I have a job with the **_redshift_** type. But it seems like it's not working, **_metrics_** are not presented, probably it didn't **_discover_** any redshift instance. Here is the configuration of that job:

```
            - type: "redshift"
              regions:
                - us-west-2
              dimensions:
                - name: ClusterIdentifier
                  value: .*
               -  name: NodeID
                  value: .*
              metrics:
                - length: 300
                  name: NetworkReceiveThroughput
                  period: 300
                  statistics:
                    - Average
                - length: 300
                  name: NetworkTransmitThroughput
                  period: 300
                  statistics:
                    - Average
                - length: 300
                  name: DatabaseConnections
                  period: 300
                  statistics:
                    - Average
                - length: 300
                  name: CPUUtilization
                  period: 300
                  statistics:
                    - Average
                - length: 300
                  name: PercentageDiskSpaceUsed
                  period: 300
                  statistics:
                    - Average
                - length: 300
                  name: HealthStatus
                  period: 300
                  statistics:
                    - Average
                - length: 300
                  name: MaintenanceMode
                  period: 300
                  statistics:
                    - Average
```

Is there something that I've missed in the configuration, like **_searchTags_** or something like that? What is mandatory for auto discovery?
