### ISSUE TITLE
Unable to pull ec2-AutoScalingGroupName-CPUUtilization metric

### ISSUE THREAD

**Issue by krishnakvr** [ivx/yet-another-cloudwatch-exporter#298]
I am trying to pull "CPUUtilization" metric from AutoScalingGroupName awsDimensions under namespace :AWS/EC2 and I am not getting any metrics. Can you please tell what I am missing ?

```
  - type: ec2
    regions:
      - sa-east-1
    searchTags:
      - Key: Name
        Value: (qa1*|pre*)
    awsDimensions:
     - AutoScalingGroupName
    metrics:
      - name: CPUUtilization
        statistics:
        - Maximum
        period: 60
        length: 180
        nilToZero: true
        addCloudwatchTimestamp: true
```
