### ISSUE TITLE
Not seeing HTTPCode_ELB_*_Count metrics.

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [ivx/yet-another-cloudwatch-exporter#302]
We are trying to get the metrics defined below from CW for our ALBs. Even though we are seeing metrics for these in the AWS CW Metrics dashboard and all of the resources are tagged, we are not getting anything besides _tg_ metrics. We are using the latest version of YACE, and our configuration should be correct. Any thoughts?

```
discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
  jobs:
  - type: alb
    length: 300
    regions:
      - us-east-1
    metrics:
     - name: HTTPCode_ELB_4XX_Count
        statistics:
          - Average
          - Sum
        period: 60
        length: 300
      - name: HTTPCode_ELB_5XX_Count
        statistics:
          - Average
          - Sum
        period: 60
        length: 300
      - name: HTTPCode_ELB_3XX_Count
        statistics:
          - Average
          - Sum
        period: 60
        length: 300
```
