### ISSUE TITLE
Add support of sts:AssumeRoleWithWebIdentity for EKS

### ISSUE THREAD

**Issue by UladzislauValchkou** [ivx/yet-another-cloudwatch-exporter#316]
Please add support of EKS service account IAM role usage instead of credentials provided in Kubernetes secret or kube2iam usage.
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by AndrewChubatiuk** [comment]
@UladzislauValchkou you can use a helm chart for official prometheus cloudwatch exporter
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-cloudwatch-exporter
You only need to override its config
```
image:
   repository: quay.io/invisionag/yet-another-cloudwatch-exporter
   tag : v0.25.0-alpha
command:
   - "/usr/local/bin/yace"
   - "-config.file=/config/config.yml"
   - "-listen-address=:9106"
serviceAccount:
   annotations:
      "eks.amazonaws.com/role-arn": <your-role-arn>
securityContext:
   runAsUser: 1000
   fsGroup: 1000
config: <your-exporter-config>
```
and setup OIDC provider for your cluster
https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
