### ISSUE TITLE
Minimal EC2 Example

### ISSUE THREAD

**Issue by jeschkies** [ivx/yet-another-cloudwatch-exporter#319]
Hi,

I am trying to setup the exporter but fail awfully. I have a `t2.small` EC2 instance running on `eu-west-1` and started YACE with the following `config.yml`

```yaml
static:
  - namespace: AWS/EC2
    name: must_be_set
    regions:
      - eu-west-1
    metrics:
      - name: CPUUtilization 
        statistics:
        - Minimum
        period: 60
        length: 30
```

and command

```
ocker run -p 5000:5000 -v "$(pwd)/yace-config.yml:/tmp/config.yml" -e AWS_ACCESS_KEY_ID=... -e AWS_SECRET_ACCESS_KEY=... quay.io/invisionag/yet-another-cloudwatch-exporter:v0.25.0-alpha -debug -config.file /tmp/config.yml
```

Yet http://localhost:5000/metrics shows only `yace_` metrics. What am I missing? I've waited for roughly twenty minutes.
