### ISSUE TITLE
Sleeping interval messed up?

### ISSUE THREAD

**Issue by BitProcessor** [ivx/yet-another-cloudwatch-exporter#335]
Docker image: `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.25.0-alpha`
Startup command: `--config.file=/opt/yace/config.yml --scraping-interval=60 --debug`

With the following config:
```
discovery:
  exportedTagsOnMetrics:
    sqs:
      - env
      - customer
      - message_type
      - queue_type
    lambda:
      - env
      - customer
      - service
  jobs:
  - type: sqs
    period: 60
    length: 60
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: ApproximateAgeOfOldestMessage
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesVisible
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesNotVisible
        statistics:
        - Average
  - type: lambda
    period: 300
    length: 3600
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: Invocations 
        statistics:
        - Sum
      - name: Duration
        statistics:
        - Average
      - name: Errors
        statistics:
        - Sum
      - name: IteratorAge
        statistics:
        - Maximum
      - name: ProvisionedConcurrencySpilloverInvocations
        statistics:
        - Sum
        period: 86400
        length: 86400
```

Yace collects the metrics on startup, next says:

```
{"level":"debug","msg":"Metrics scraped.","time":"2021-03-11T12:37:11Z"}
{"level":"debug","msg":"Sleeping at regular sleep interval 86400","time":"2021-03-11T12:37:11Z"}
```

Somehow it seems that that last - metric level - period or length is taken as sleep interval? 

Further testing:
Changing the config to:
```
discovery:
  exportedTagsOnMetrics:
    sqs:
      - env
      - customer
      - message_type
      - queue_type
    lambda:
      - env
      - customer
      - service
  jobs:
  - type: sqs
    period: 60
    length: 60
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: ApproximateAgeOfOldestMessage
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesVisible
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesNotVisible
        statistics:
        - Average
  - type: lambda
    period: 300
    length: 3600
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: Invocations 
        statistics:
        - Sum
      - name: Duration
        statistics:
        - Average
      - name: Errors
        statistics:
        - Sum
      - name: IteratorAge
        statistics:
        - Maximum
      - name: ProvisionedConcurrencySpilloverInvocations
        statistics:
        - Sum
        # period: 86400
        # length: 86400
```
Results in:
```
{"level":"debug","msg":"Metrics scraped.","time":"2021-03-11T12:46:07Z"}
{"level":"debug","msg":"Sleeping at regular sleep interval 3600","time":"2021-03-11T12:46:07Z"}
```

Here it seems to have taken the `length: 3600` from the lambda job.

Either I am doing something terribly wrong config-wise, or something is a bit off?
