### ISSUE TITLE
The startTime and endTime of Auto-discovery job are not relevant to the moment of the scraping.

### ISSUE THREAD

**Issue by Kirchen99** [ivx/yet-another-cloudwatch-exporter#337]
https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.25.0-alpha/aws_cloudwatch.go#L158
**What did you do?**
I configured the exporter to export S3 metrics. The scrape interval is 5 minutes. My config:
```
discovery:
      exportedTagsOnMetrics:
        s3:
          - BucketName
          - FilterId
      searchTags:
        - key: "xxx"
          value: xxxx
      jobs:
      - type: s3
        regions:
          - eu-central-1
        awsDimensions:
          - FilterId
          - BucketName
        metrics:
          - name: BytesUploaded
            statistics:
            - Sum
            period: 86400
        metrics:
          - name: AllRequests
            statistics:
            - Sum
            period: 86400
```

**What did you expect to see?**
When I had deployed the exporter on 13:00 2021.03.10, I expected to see the data with startTime 13:00 2021.03.10 and endTime 13:02 2021.03.10 after the first scrape and the data with startTime 13:03 2021.03.10 and endTime 13:05 2021.03.10 after the second scrape and so on. Because the scrape interval is 5 minutes and length default is 2 minutes.

**What did you see instead? Under which circumstances?**
I see the data with startTime 13:00 2021.03.10 and endTime 13:02 2021.03.10 after the first scrape and the data with startTime **_13:02_** 2021.03.10 and endTime **_13:04_** 2021.03.10 after the second scrape.

**What is the Problem:**
The startTime and endTime of Auto-discovery job are not relevant to the moment of the scraping. It only depends on the time when the program starts and `length`.
