### ISSUE TITLE
Connection refused after hours

### ISSUE THREAD

**Issue by Lucuz91** [ivx/yet-another-cloudwatch-exporter#338]
Hi, I have a problem, after a few hours the exporter starts to work intermittently. The logs are the following:

```
{     "level": "info",     "msg": "Parse config..",     "time": "2021-03-16T14:59:10Z" }
{     "level": "info",     "msg": "Startup completed",     "time": "2021-03-16T14:59:10Z" }
{     "level": "info",     "msg": "Couldn't describe resources for region eu-west-1: RequestError: send request failed\ncaused by: Post \"https://tagging.eu-west-1.amazonaws.com/\": dial tcp: lookup tagging.eu-west-1.amazonaws.com on 10.10.133.22:53: read udp 172.17.0.15:35152->10.10.133.22:53: read: connection refused\n",     "time": "2021-03-17T01:03:03Z" }
{     "level": "info",     "msg": "Couldn't describe resources for region eu-west-1: RequestError: send request failed\ncaused by: Post \"https://tagging.eu-west-1.amazonaws.com/\": dial tcp: lookup tagging.eu-west-1.amazonaws.com on 10.10.133.22:53: read udp 172.17.0.15:40928->10.10.133.22:53: read: connection refused\n",     "time": "2021-03-17T01:03:03Z" }
{     "level": "info",     "msg": "Couldn't describe resources for region eu-west-1: RequestError: send request failed\ncaused by: Post \"https://tagging.eu-west-1.amazonaws.com/\": dial tcp: lookup tagging.eu-west-1.amazonaws.com on 10.10.133.22:53: read udp 172.17.0.15:46779->10.10.133.22:53: read: connection refused\n",     "time": "2021-03-17T01:03:05Z" }
```
I have other containers with yace, and none have this problem (but the others have version v0.23.0-alpha and don't have the scraping interval at 60, but the default at 300) The logs are the following "", sometimes yes it picks up and produces data, otherwise it continues to respond, but giving all values to NaN. Restarting the container everything works out.
This is an example the output when "fail":

```
# HELP aws_alb_tg_healthy_host_count_average Help is not implemented yet.
# TYPE aws_alb_tg_healthy_host_count_average gauge
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/awsd04-analytics-delivery/85f9c3f41b9e1331",dimension_TargetGroup="targetgroup/awsd04-analitycs-collector/d63c8d3becb6598a",name="arn:aws:elasticloadbalancing:eu-west-1:xxx:targetgroup/awsd04-analitycs-collector/d63c8d3becb6598a",region="eu-west-1",tag_Name="awsd04-ecs-analytics-collector"} NaN
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/awsd04-thron-balancer-static-1/69abdf19cd2f28fc",dimension_TargetGroup="targetgroup/awsd04-thron-ec2-core/9b9fe81a447e255c",name="arn:aws:elasticloadbalancing:eu-west-1:xxx:targetgroup/awsd04-thron-ec2-core/9b9fe81a447e255c",region="eu-west-1",tag_Name="awsd04-thron-ec2-core"} NaN
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/awsd04-thron-balancer-static-1/69abdf19cd2f28fc",dimension_TargetGroup="targetgroup/awsd04-thron-ec2-intelligence/bf45636966fb81ef",name="arn:aws:elasticloadbalancing:eu-west-1:xxx:targetgroup/awsd04-thron-ec2-intelligence/bf45636966fb81ef",region="eu-west-1",tag_Name="awsd04-thron-ec2-intelligence"} NaN
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/awsd04-thron-ecs-cdn-origin-1/37ae7a63d9dec09e",dimension_TargetGroup="targetgroup/awsd04-ecs-cdn-origin/a687b2fb4b4fcb0a",name="arn:aws:elasticloadbalancing:eu-west-1:xxx:targetgroup/awsd04-ecs-cdn-origin/a687b2fb4b4fcb0a",region="eu-west-1",tag_Name="awsd04-thron-ecs-cdn-origin"} NaN
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/awsd04-thron-ecs-core-console-1/db8a38bbd82bb653",dimension_TargetGroup="targetgroup/awsd04-bacheca-web/a91e52b62f4d3cb1",name="arn:aws:elasticloadbalancing:eu-west-1:xxx:targetgroup/awsd04-bacheca-web/a91e52b62f4d3cb1",region="eu-west-1",tag_Name="awsd04-bacheca-web"} NaN
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/awsd04-thron-ecs-core-console-1/db8a38bbd82bb653",dimension_TargetGroup="targetgroup/awsd04-ce-manager/b43da15f583bcfae",name="arn:aws:elasticloadbalancing:eu-west-1:xxx:targetgroup/awsd04-ce-manager/b43da15f583bcfae",region="eu-west-1",tag_Name="awsd04-ce-manager"} NaN
```

The application is on a container (ECS) on AWS, the CPU and RAM metrics show no strange behavior.
Yace is set with a 60 second scraping interval.
The configuration is as follows:
```
---

discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
    alb:
      - Name
  jobs:
    - regions:
        - eu-west-1
      type: elb
      period: 60
      length: 60
      delay: 60
      searchTags:
        - Key: Name
          Value: ^(aws(d|q|b)?(04|01)-thron-balancer-main)$
      metrics:
        - name: RequestCount
          statistics:
            - Sum
        - name: Latency
          statistics:
            - Average
        - name: UnHealthyHostCount
          statistics:
            - Average
        - name: HealthyHostCount
          statistics:
            - Average
        - name: HTTPCode_Backend_5XX
          statistics:
            - Sum
        - name: HTTPCode_ELB_5XX
          statistics:
            - Sum
    - regions:
        - eu-west-1
      type: alb
      period: 60
      length: 60
      delay: 60
      metrics:
        - name: RequestCount
          statistics:
            - Sum
        - name: TargetResponseTime
          statistics:
            - Average
        - name: UnHealthyHostCount
          statistics:
            - Average
        - name: HealthyHostCount
          statistics:
            - Average
        - name: HTTPCode_Target_5XX_Count
          statistics:
            - Sum
        - name: HTTPCode_ELB_5XX_Count
          statistics:
            - Sum
    - regions:
        - eu-west-1
      type: ecs-svc
      period: 60
      length: 60
      delay: 60
      metrics:
        - name: CPUUtilization
          statistics: [Average]
        - name: MemoryUtilization
          statistics: [Average]
```
The version of yace is v0.25.0-alpha.
Anyone have any idea what it could be?
