### ISSUE TITLE
Gaps on one AWS account and works fine on other account

### ISSUE THREAD

**Issue by vitali-raikov** [ivx/yet-another-cloudwatch-exporter#340]
Hi, we have YACE installed in two different accounts with exactly same config and same Prometheus scraping configuration, however in one case we have gaps and in other it seems that everything is working as expected.

Take for example ReadIOPS metrics from RDS from problematic account
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/588383/111802176-5ecffd00-88d6-11eb-91b5-e22ff6391d20.png">

And this is how it works on the other account
<img width="2033" alt="image" src="https://user-images.githubusercontent.com/588383/111802385-963ea980-88d6-11eb-8ddc-1fcfbaf870ec.png">

Query looks like this:

```
avg by (dimension_DBInstanceIdentifier) (aws_rds_read_iops_average{dimension_DBInstanceIdentifier="DB_NAME"})
```

We are running it on Kubernetes, we have a separate Prometheus job to scrape metrics which is identical on both accounts which looks like this

```
- job_name: cloudwatch-exporter
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
    separator: ;
    regex: (prometheus-cloudwatch-exporter)
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_sidecar_istio_io_status, __meta_kubernetes_pod_annotation_prometheus_io_scheme]
    separator: ;
    regex: ((;.*)|(.*;http))
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_istio_mtls]
    separator: ;
    regex: (true)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  metric_relabel_configs:
  - separator: ;
    regex: instance
    replacement: $1
    action: labeldrop
  kubernetes_sd_configs:
  - role: pod
```

And this is full YACE config, again identical on both accounts (Provisioned through Helm chart with same config)

```
  discovery:
    jobs:
    - type: rds
      addCloudwatchTimestamp: true
      length: 60
      period: 60
      delay: 120
      regions:
        - eu-central-1
        - us-west-2
      metrics:
        - name: 'WriteIOPS'
          statistics:
            - Average

        - name: 'ReadIOPS'
          statistics:
            - Average

        - name: 'DatabaseConnections'
          statistics:
            - Average

        - name: 'ReplicaLag'
          statistics:
            - Average

        - name: 'CPUUtilization'
          statistics:
            - Average

        - name: 'FreeableMemory'
          statistics:
            - Average

        - name: 'FreeStorageSpace'
          statistics:
            - Average

    # Elasticache
    - type: ec
      regions:
        - eu-central-1
        - us-west-2
      addCloudwatchTimestamp: true
      length: 60
      period: 60
      delay: 120
      metrics:
        - name: 'FreeMemory'
          statistics:
            - Average

        - name: 'CPUUtilization'
          statistics:
            - Average

    - type: ec2
      regions:
        - eu-central-1
        - us-west-2
      addCloudwatchTimestamp: true
      length: 60
      period: 60
      delay: 120
      metrics:
        - name: 'StatusCheckFailed_System'
          statistics:
            - Average
```

Version: 0.26.3-alpha (but it was same with 0.26.5 as well.
And these are the arguments for running YACE

```
          command:
            - "yace"
            - "--config.file=/etc/yace/config.yml"
            - "--scraping-interval=60"
```

This also applies to other metrics and not RDS specific as well. Some other databases might have not have these gaps but you an still see that resolution is twice worse than on other account.

Needless to say that resolution of metrics in Cloudwatch directly looks fine.

Not saying that YACE is at fault here but I am quickly running out of options what could be wrong here and would appreciate any suggestions.
