### ISSUE TITLE
Scrapes running in EKS fail after first scrape

### ISSUE THREAD

**Issue by rrusso1982** [ivx/yet-another-cloudwatch-exporter#347]
I have YACE running in EKS using a service account with an assumed role.  Before the upgrade to 0.26 this worked fine.  After the upgrade it appears that after the first scrape is completed the next scrape returns all NaN data.

Example:
First Scrape:
```aws_dynamodb_consumed_read_capacity_units_average{account_id="XXXXXX",dimension_global_secondary_index_name="",dimension_table_name="entitlements-store-us-production-v1",name="arn:aws:dynamodb:us-east-1:XXXXXXX:table/entitlements-store-us-production-v1",region="us-east-1",tag_environment="production",tag_name="entitlements-store-us-production-v1",tag_role="dynamodb",tag_service="entitlements-store-us"} 0.5 1616779020000```

Second Scrape:
```aws_dynamodb_consumed_read_capacity_units_average{account_id="XXXXXXX",dimension_global_secondary_index_name="",dimension_table_name="entitlements-store-us-production-v1",name="arn:aws:dynamodb:us-east-1:XXXXXX:table/entitlements-store-us-production-v1",region="us-east-1",tag_environment="production",tag_name="entitlements-store-us-production-v1",tag_role="dynamodb",tag_service="entitlements-store-us"} NaN```

**Comment by bryan-kc** [comment]
I have similar issues running on 0.26.3-alpha. 

I have it setup with the configuration found on PromCat (https://promcat.io/apps/aws-alb) 

This is the deployment manifest I am using
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace
  namespace: cloudwatch-exporter
spec:
  selector:
    matchLabels:
      app: yace
  replicas: 1
  template:
    metadata:
      labels:
        app: yace
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: yace
          image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.26.3-alpha
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/tmp/config.yml"
          ports:
            - name: app
              containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /tmp
            - name: yace-credentials
              mountPath: /exporter/.aws/credentials
              subPath: credentials
          securityContext:
            runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: yace
        - secret:
            defaultMode: 420
            secretName: yace-credentials
          name: yace-credentials
```

I did not configure `roleArn` in my config.yml, and I have encoded AWS credentials using an IAM User in the `yace-credentials` secret with the following policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CloudWatchExporterPolicy",
            "Effect": "Allow",
            "Action": [
                "tag:GetResources",
                "cloudwatch:ListTagsForResource",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:GetMetricData",
                "cloudwatch:ListMetrics"
            ],
            "Resource": "*"
        }
    ]
}
```

With the PromCat config I can get metrics scraped twice (0 minute, 5 minute), but at the 10 minute scrape the NaN values are returned.

**Comment by rrusso1982** [comment]
More information:  I tried removing the service account that I was using so it would use the node's permissions and that resulted in the same situation.

Also I rolled back to 0.25 and this does not occur in that version.

**Comment by bryan-kc** [comment]
I have a feeling that the change introduced in this code block is what is causing issues as the STS token expires around that time.

https://github.com/ivx/yet-another-cloudwatch-exporter/blob/aa06bfea88a4b4d5634739584a6293bd0f775136/aws_cloudwatch.go#L50-L63
https://github.com/ivx/yet-another-cloudwatch-exporter/blob/aa06bfea88a4b4d5634739584a6293bd0f775136/abstract.go#L28

**Comment by rrusso1982** [comment]
@bryan-kc I was thinking the same thing but it is odd since a new session in theory is being created each time....

**Comment by rrusso1982** [comment]
I have a suspicion it is because the cloudwatch client is not being passed down to:

https://github.com/ivx/yet-another-cloudwatch-exporter/blob/fba13ab956693352f61b4a6e974d05dac1af8dc5/aws_cloudwatch.go#L144

and 

https://github.com/ivx/yet-another-cloudwatch-exporter/blob/fba13ab956693352f61b4a6e974d05dac1af8dc5/aws_cloudwatch.go#L192

yet it is making queries to cloudwatch...

**Comment by haarchri** [comment]
we have running latest master wich merged #350 but it looks like after 1 hour the exporter has problems to authenticate we see lot of metrics with NaN - any idea ?

**Comment by haarchri** [comment]
we also tested now IAMUser with Access Credentials but also here we see the issue that after 5 minutes no scraping is executed - also in debug we no messages that indicates an issue

**Comment by JayJong** [comment]
Just wanna share, Im using 0.26.3-alpha, all my metrics are returning NaN after second scrape, after i add "--decoupled-scraping=false", i'm getting values for my metrics again

**Comment by haarchri** [comment]
we can confirm we also disabled decoupled-scraping and running every individual aws metric in individual deployments

**Comment by BitProcessor** [comment]
After facing numerous NaN issues after adding RDS metrics (had already Lambda + SQS), I'm now testing with 0.27.0 (made image myself base on the commit on master) + decouple-scraping=false + prometheus set to a 60s scraping interval. 

🤞🏻

**Comment by BitProcessor** [comment]
18h and still working.

Previously, it worked fine with the decoupled-scraping and the SQS + Lambda config on 0.26.3.
But as soon as I added the RDS config (and EC) , it would stop returning metrics after 3-ish hours (0.26.3 and 0.27.0)

This is with an image build based on https://github.com/ivx/yet-another-cloudwatch-exporter/commit/02f97ff5f589569189496e5023eebbbceda7bdf6

Commandline option:
`--decoupled-scraping=false`

Prometheus: 
```
  - job_name: 'yace'
    scrape_interval: 60s
    static_configs:
    - targets: ['yace.<hidden>:5000']
```

And config:
```
discovery:
  exportedTagsOnMetrics:
    sqs:
      - env
      - customer
      - message_type
      - queue_type
    lambda:
      - env
      - customer
      - service
    rds:
      - env
      - customer
    ec:
      - env
      - customer
  jobs:
    - type: lambda
      regions:
        - eu-west-1
      period: 300
      length: 3600   
      metrics:
        - name: Duration
          statistics:
            - Average
        - name: Invocations 
          statistics:
            - Sum
        - name: Errors
          statistics:
          - Sum
    - type: rds
      regions:
        - eu-west-1
      period: 300
      length: 3600
      metrics:
        - name: CPUUtilization
          statistics:
          - Average
        - name: DatabaseConnections
          statistics:
          - Average
        - name: ReadIOPS
          statistics:
          - Average
        - name: WriteIOPS
          statistics:
          - Average
    - type: sqs
      regions:
        - eu-west-1
      period: 300
      length: 3600
      searchTags:
        - key: env
          value: dev|staging|prod
      metrics:
        - name: ApproximateAgeOfOldestMessage
          statistics:
          - Average
        - name: ApproximateNumberOfMessagesVisible
          statistics:
          - Average
        - name: ApproximateNumberOfMessagesNotVisible
          statistics:
          - Average
    - type: ec
      regions:
        - eu-west-1
      period: 300
      length: 3600
      metrics:
        - name: BytesUsedForCache
          statistics:
          - Average
```
