### ISSUE TITLE
Unable to fetch docdb FreeLocalStorage

### ISSUE THREAD

**Issue by JnMik** [ivx/yet-another-cloudwatch-exporter#353]
Hello guys,
I've been using cloud-exporter for a while now, it's all working well.

Today I implemented docdb metrics, they all seem to work but one (FreeLocalStorage).
Curl the /metrics route, I don't see it appearing there 

Tried to grep as well
_curl -i http://yace.monitoring.svc.cluster.local:5000/metrics | grep storage_
returns nothing

Anyone else has this issue ? 

I'm pretty sure my configuration is well written 
![image](https://user-images.githubusercontent.com/4965516/113186256-6a4fec00-9225-11eb-9fb0-95d3afe1dba7.png)

**Comment by haarchri** [comment]
on our side it is working with docdb

![image](https://user-images.githubusercontent.com/21083497/113871535-4bb49c80-97b3-11eb-8b93-d0f6ae36076a.png)


```
        - name: FreeLocalStorage
          statistics:
            - Average
          period: 300
          length: 3600
```
