### ISSUE TITLE
Getting duplicate RDS metrics

### ISSUE THREAD

**Issue by v1ctorrhs** [ivx/yet-another-cloudwatch-exporter#373]
I'm running v0.26.3-alpha inside an EKS cluster.

Authentication is handled using a service account that has an IAM role attached to it.

I'm running the following yace-exporter configuration for a single RDS Postgresql instance and I keep getting the same metric 5 times with different labels. 
```
config: |
  discovery:
    jobs:
    - type: rds
      regions:
      - us-east-1
      searchTags:
        - key: environment
          value: test
      metrics:
        - name: NetworkReceiveThroughput
          statistics:
          - Average
          period: 300
          length: 3600
```

```# TYPE aws_rds_network_receive_throughput_average gauge
aws_rds_network_receive_throughput_average{account_id="XXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="",dimension_EngineName="",name="global",region="us-east-1"} 2217.2519934646384
aws_rds_network_receive_throughput_average{account_id="XXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="",dimension_EngineName="postgres",name="global",region="us-east-1"} 2217.2519934646384
aws_rds_network_receive_throughput_average{account_id="XXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="db.t3.medium",dimension_EngineName="",name="global",region="us-east-1"} 2217.2519934646384
aws_rds_network_receive_throughput_average{account_id="XXXXX",dimension_DBInstanceIdentifier="monitoring-grafana-postgres",dimension_DatabaseClass="",dimension_EngineName="",name="arn:aws:rds:us-east-1:XXXXX:db:monitoring-grafana-postgres",region="us-east-1"} 2217.2519934646384
```

Adding another metric results in the same behavior

```aws_rds_maximum_used_transaction_ids_average{account_id="XXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="",dimension_EngineName="",name="global",region="us-east-1"} 2545.4
aws_rds_maximum_used_transaction_ids_average{account_id="XXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="",dimension_EngineName="postgres",name="global",region="us-east-1"} 2545.4
aws_rds_maximum_used_transaction_ids_average{account_id="XXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="db.t3.medium",dimension_EngineName="",name="global",region="us-east-1"} 2545.4
aws_rds_maximum_used_transaction_ids_average{account_id="XXXXX",dimension_DBInstanceIdentifier="monitoring-grafana-postgres",dimension_DatabaseClass="",dimension_EngineName="",name="arn:aws:rds:us-east-1:XXXXX:db:monitoring-grafana-postgres",region="us-east-1"} 2545.4
```

**Comment by sepich** [comment]
It's because all possible dimensions are discovered after https://github.com/ivx/yet-another-cloudwatch-exporter/pull/315
You can revert to `v0.25.0-alpha` and use:
```
    - type: rds
      regions:
      - us-east-1
      searchTags:
        - key: environment
          value: test
      awsDimensions: [DBInstanceIdentifier]
      metrics:
        - name: NetworkReceiveThroughput
          statistics:
          - Average
          period: 300
          length: 3600
```

**Comment by dmitry-tiger** [comment]
Can we add old behaviour as a feature? 
Searching or making graphs through different sets of labels for the same metric become much trickier. 
With that behaviour you also have to make aggregation through metric more carefully to avoid duplicates.

**Comment by dfredell** [comment]
Might be the same issue as  #404

**Comment by alext** [comment]
I've hit this same issue (version 0.64.0). I found that adding `dimensionNameRequirements` to filter out metrics that are not instance-specific resolved it for me:
eg:
```
jobs:
  - type: AWS/RDS
    searchTags:
      - key: my_tag
        value: my_tag_Value
    dimensionNameRequirements:
      - DBInstanceIdentifier
    period: 60
    length: 300
    addCloudwatchTimestamp: true
    metrics:
      - name: FreeStorageSpace
        statistics:
          - Minimum
```
