### ISSUE TITLE
How to tell Yace to include dimension in the metric ? 

### ISSUE THREAD

**Issue by JnMik** [ivx/yet-another-cloudwatch-exporter#374]
I'm trying to add "ShardId" dimension in my kinesis metric, but can't figure it out.

![image](https://user-images.githubusercontent.com/4965516/116731190-63003780-a9b7-11eb-8346-ee1b6da9a303.png)

I tried adding this:

```
discovery:
    exportedTagsOnMetrics:
      kinesis:
        - ShardId
```

I also tried with the following one that seemed to be an existing property in the original cloudwatch-exporter.

```
- type: kinesis
      aws_dimensions: ["ShardId"]
```

No success.

Is that even possible ?
Thanks !
