### ISSUE TITLE
rds metrics coming intermittently 

### ISSUE THREAD

**Issue by bhupixb** [ivx/yet-another-cloudwatch-exporter#378]
Hi everyone.
We are running v0.25.0-alpha version of YACE for fetching rds metrics from cloudwatch.

We are using following yace-exporter configuration:
1) ConfigMap
```
discovery:
  exportedTagsOnMetrics:
    rds:
    - info:name
    - org:tenant
    - org:bu
    - org:team
    - service:environment
  jobs:
  - type: rds
    searchTags:
    - Key: service:environment
      Value: preprod
    regions:
      - ap-south-1
    metrics:
      - name: CPUUtilization
        statistics:
        - Average
        period: 60
        length: 180 
      ...
   # remaining rds metrics follow the same syntax as CPUUtilization
```
2) deployment args
```
containers:
  - args:
      - '--decoupled-scraping=false'
      - '--config.file=/tmp/config.yml'
    image: 'quay.io/invisionag/yet-another-cloudwatch-exporter:v0.25.0-alpha'
```
Here is a sample of our prometheus metric:
```
aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier="XXX",endpoint="XXX",instance="XXX",job="",name="XXX",namespace="XXX",pod="XXX",region="",service="",tag_org_bu="",tag_org_team="",tag_org_tenant="",tag_service_environment=""} <value>
```
The issue that we are facing is that in every 5 minutes, metrics data for 2 consecutive minutes is missing, Prometheus shows NaN for that interval(in which data is missing).
<a href="https://ibb.co/y8jXVwF"><img src="https://i.ibb.co/y8jXVwF/grafana-dashboard.png" alt="grafana-dashboard" border="0"></a>

Things we tried:
1) added arg '`--decoupled-scraping=false`' as mentioned here https://github.com/ivx/yet-another-cloudwatch-exporter#decoupled-scraping
2) added '`--scraping-interval=60`' 
3) tried different period e.g. 30, 60, 120 etc. 
We don't see any improvement after try above things.

Can someone please help/guide what are we doing wrong?

**Comment by BitProcessor** [comment]
Can you try with?
```
      period: 300
      length: 3600
```

**Comment by bhupixb** [comment]
@BitProcessor  yeah, we tried with period: 300, length:300 & data is coming consistently but the problem is that _with period length of 300, our metrics won't register spikes very quickly._

**Comment by akatumalla27** [comment]
I am facing the same issue. I have tried @BitProcessor's suggestion of period as 300 and length 3600. This doesn't work as well. 

```
discovery:
  jobs:
  - type: rds
    regions:
      - us-east-2
    searchTags:
      - key: name
        value: catapult-db
    metrics:
      - name: FreeStorageSpace
        statistics:
        - Average
        period: 300
        length: 3600

```
