### ISSUE TITLE
ELB labels not being honoured - 

### ISSUE THREAD

**Issue by alam0rt** [ivx/yet-another-cloudwatch-exporter#379]
0.27.0-alpha

I have found that while my NLB metrics are correctly labeled, my ELB metrics are not:

```yaml
discovery:
  exportedTagsOnMetrics:
    elb:
    - kubernetes.io/service-name
    nlb:
    - kubernetes.io/service-name
  ...
  - type: elb
    regions:
      - some-region
    searchTags:
      - key: kubernetes.io/service-name
        value: .*
```

It's odd because if I look at `aws_elb_info{}`, I can see the correct labels and the searchTags are honoured:

```
aws_elb_info{name="LBARN",tag_kubernetes_io_cluster_clustername="owned",tag_kubernetes_io_service_name="istio-system/istio-ingressgateway"} 0
```

but they are not on the scraped metrics

```
aws_elb_healthy_host_count_minimum{account_id="someaccount",dimension_AvailabilityZone="someaz",dimension_LoadBalancerName="lbname",dimension_Namespace="",dimension_Service="",name="global",region="some-region",tag_kubernetes_io_service_name=""} 2
```
