### ISSUE TITLE
Unable to collect metrics of Instance launched in AZ us-west-2c

### ISSUE THREAD

**Issue by neeleshg** [ivx/yet-another-cloudwatch-exporter#390]
YACE Version: 0.27.0-alpha
I am trying to collect EC2 instance Cloudwatch Metrics.
I noticed that it is not collecting metrics of Instances which are running in `us-west-2c` Availability Zone.
It is showing `NaN` in front of metric. I can see metric data for other instances.
My configuration:
```
discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
  jobs:
  - type: ec2
    regions:
      - us-west-2
    searchTags:
      - key: Name
        value: xxxxx
    metrics:
      - name: CPUUtilization
        statistics:
        - Sum
        period: 300
        length: 300
      - name: NetworkIn
        statistics:
        - Sum
        period: 300
        length: 300
      - name: NetworkOut
        statistics:
        - Sum
        period: 300
        length: 300
```
Response ->
```
root@localhost:/# curl http://localhost:5000/metrics |grep cpu
aws_ec2_cpuutilization_sum{account_id="<account_id>",dimension_AutoScalingGroupName="",dimension_InstanceId="i-111111",name="arn:aws:ec2:us-west-2:<account_id>:instance/i-111111",region="us-west-2",tag_Name="xxxxx"} NaN
```
I dont know if it is expected but it did not even get AutoScaling Group Name .
