### ISSUE TITLE
Incorrect data between official CloudWatch exporter and YACE

### ISSUE THREAD

**Issue by setevoy2** [ivx/yet-another-cloudwatch-exporter#395]
On the screenshot on the top - two graphs for metrics collected by an [official CloudWatch exporter](https://github.com/prometheus/cloudwatch_exporter).
At the bottom - the same metrics, but collected by the YACE.

Both have similar configs for metrics but represent absolutely different data.
Any ideas?

I'm running a script that sends an email every 10 seconds, so Overall statistic CW seems to be correct, and it's the same as it's represented in the AWS CloudWatch Console. 

CloudWatch Exporter config:

```
region: us-east-1
set_timestamp: false
delay_seconds: 60

metrics:

 - aws_namespace: AWS/SES
   aws_metric_name: Send

 - aws_namespace: AWS/SES
   aws_metric_name: Delivery

 - aws_namespace: AWS/SES
   aws_metric_name: Bounce

 - aws_namespace: AWS/SES
   aws_metric_name: Complaint

 - aws_namespace: AWS/SES
   aws_metric_name: Reputation.BounceRate

 - aws_namespace: AWS/SES
   aws_metric_name: Reputation.ComplaintRate
```

And YACE config:

```
  discovery:
    jobs:
  - type: ses
    regions:
      - us-east-1
    metrics:

      - name: Reputation.BounceRate
        statistics: [Sum]
        period: 60
        length: 60
#        period: 86400
#        length: 86400

      - name: Reputation.ComplaintRate
        statistics: [Sum]
        period: 60
        length: 60
#        period: 86400
#        length: 86400

      - name: Delivery
        statistics: [Sum]
        period: 60

      - name: Bounce
        statistics: [Sum]
        period: 60

      - name: Compliant
        statistics: [Sum]
        period: 60

      - name: Send
        statistics:
        - Sum
#        period: 60
#        length: 60
```

I've tried to play with the `period` and `length` for YACE, but no luck.

![Screenshot_20210609_170619](https://user-images.githubusercontent.com/7965314/121370035-0ba19f80-c945-11eb-95b8-3e541e1e6ee6.png)
![Screenshot_20210609_170702](https://user-images.githubusercontent.com/7965314/121370124-1fe59c80-c945-11eb-9933-145cbba04215.png)
