### ISSUE TITLE
How to Configure the Exporter to Compute Sum Over Time in Prometheus with Not Even Data Points?

### ISSUE THREAD

**Issue by Kirchen99** [ivx/yet-another-cloudwatch-exporter#403]
Hi All,

We have an Amazon Lambda function which runs in not even time intervals and creates a datapoint after each run. We want to use sum_over_time in Prometheus with a changeable time period to compute the sum. But we have no idea, how to configure the YACE. Could someone help us?

Our metric looks like follows:

![datapoints](https://user-images.githubusercontent.com/9981745/122546052-da089280-d02e-11eb-9e7b-f388e725958a.png)

**Comment by ljluestc** [comment]
```
scrape_configs:
  - job_name: yace-lambda
    aws_region: us-east-1
    metrics:
      - aws_namespace: AWS/Lambda
        aws_metric_name: Invocations
        aws_dimensions: [FunctionName]
    relabel_configs:
      - source_labels: [__metric__]
        target_label: job
      - source_labels: [FunctionName]
        target_label: function_name
      - source_labels: [__value__]
        target_label: value

```
