### ISSUE TITLE
Missing metrics for Buckets without any tag

### ISSUE THREAD

**Issue by svenwltr** [ivx/yet-another-cloudwatch-exporter#415]
It looks like the exporter is ignoring S3 Buckets, that do not have any tag. When running it only shows a few buckets, which are this that have tags and others are missing. As soon as I add a tag to a Bucket that does not have one before, it shows up in the metrics.

This is my config:

```yaml
discovery:
  jobs:
    - type: s3
      addCloudwatchTimestamp: true
      length: 172800
      period: 86400
      regions:
      - eu-west-1
      - us-west-1
      - us-west-2
      - eu-central-1
      roles:
      - roleArn: "arn:aws:iam::xxxxxxxxxxxx:role/cloudwatch-exporter" # production
      - roleArn: "arn:aws:iam::yyyyyyyyyyyy:role/cloudwatch-exporter" # common
      metrics:
        - name: NumberOfObjects
          statistics:
            - Average
        - name: BucketSizeBytes
          statistics:
            - Average
```

The logs do not indicate any error:

```
{"level":"info","msg":"Parse config..","time":"2021-07-12T13:42:56Z"}
{"level":"info","msg":"Startup completed","time":"2021-07-12T13:42:56Z"}
```

**Comment by be4ndr** [comment]
The same issue for ElastiCache. 
No metrics on cluster without any tags. After I added a tag, the metrics for this cluster was successfully grabbed by YACE.
```
config:
  discovery:
    jobs:
    - type: ec
      period: 300
      length: 300
      regions:
      - eu-central-1
      metrics:
      - name: NewConnections
        statistics:
        - 'Average'
      - name: CurrConnections
        statistics:
      - name: CPUUtilization
        statistics:
        - 'Average'
      - name: EngineCPUUtilization
```
