### ISSUE TITLE
Athena - different values for ProcessedBytes

### ISSUE THREAD

**Issue by cgrim-cz** [ivx/yet-another-cloudwatch-exporter#417]
We setup exporting of Athena metrics from CloudWatch using YACE version **0.28.0-alpha** and are seeing strange thing in metric **ProcessedBytes**. Values for other metrics seem to be correct.

This is what is exported into Prometheus:
![aws_athena_processed_bytes_average](https://user-images.githubusercontent.com/39614988/125597104-4c1f2251-3c00-4ca8-90ea-72ba1552cd74.png)

But when I call AWS API by myself:
```console
aws cloudwatch get-metric-statistics --metric-name ProcessedBytes --dimensions Name=QueryState,Value=SUCCEEDED Name=QueryType,Value=DML --namespace AWS/Athena --statistics Average --period 300 --start-time 2021-07-14T07:00:00Z --end-time 2021-07-14T07:20:00Z
```
 I receive completely different values
```json
{
    "Label": "ProcessedBytes",
    "Datapoints": [
        {
            "Timestamp": "2021-07-14T07:10:00+00:00",
            "Average": 142312839.85714287,
            "Unit": "Bytes"
        },
        {
            "Timestamp": "2021-07-14T07:15:00+00:00",
            "Average": 3420.5714285714284,
            "Unit": "Bytes"
        },
        {
            "Timestamp": "2021-07-14T07:00:00+00:00",
            "Average": 3607.6666666666665,
            "Unit": "Bytes"
        },
        {
            "Timestamp": "2021-07-14T07:05:00+00:00",
            "Average": 148993.83333333334,
            "Unit": "Bytes"
        }
    ]
}
```
There should be 142312839.8 (142.3 MB) and not 5411.5 (5.4 kB) at time 7:10.

`get-metric-data` command returns the same result.
```console
aws cloudwatch get-metric-data --start-time 2021-07-14T07:00:00Z --end-time 2021-07-14T07:20:00Z --metric-data-queries '[{"Id":"id_1", "MetricStat": {"Period": 300, "Stat": "Average", "Metric": {
"Namespace": "AWS/Athena", "MetricName": "ProcessedBytes", "Dimensions": [{"Name":"QueryState", "Value": "SUCCEEDED"}, {"Name":"QueryType", "Value": "DML"}]}}, "ReturnData": true}]'
```
```json
{
    "MetricDataResults": [
        {
            "Id": "id_1",
            "Label": "ProcessedBytes",
            "Timestamps": [
                "2021-07-14T07:15:00+00:00",
                "2021-07-14T07:10:00+00:00",
                "2021-07-14T07:05:00+00:00",
                "2021-07-14T07:00:00+00:00"
            ],
            "Values": [
                3420.5714285714284,
                142312839.85714287,
                148993.83333333334,
                3607.6666666666665
            ],
            "StatusCode": "Complete"
        }
    ],
    "Messages": []
}
```

Here is our yace configuration:
```yaml
    discovery:
      jobs:
      - type: athena
        regions:
          - eu-west-1
        period: 60
        length: 300
        metrics:
          - name: EngineExecutionTime
            statistics:
            - Average
          - name: ProcessedBytes
            statistics:
            - Average
          - name: QueryPlanningTime
            statistics:
            - Average
          - name: QueryQueueTime
            statistics:
            - Average
          - name: ServiceProcessingTime
            statistics:
            - Average
          - name: TotalExecutionTime
            statistics:
            - Average
```
I also tried different values for `period` and `length` but still with the same results or with gaps.

For example in CloudWatch I can see that ProcessedBytes are still changing between 3 kB and 0.5 GB but in Prometheus it is still between 3 kB and 6 kB. There are no peeks.

Do you have any idea what can be wrong? Thank you
