### ISSUE TITLE
Improve documentation for static metrics by some examples e.g. for s3

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [ivx/yet-another-cloudwatch-exporter#43]
Hello the project itself is very interesting, but for some reason i cannot get the metrics at all, i start to use with this simple config

```
static:
  - namespace: AWS/S3
    region: us-east-1
    metrics:
      - name: BucketSizeBytes
        statistics:
          - Average
        period: 86400
        length: 172800
        disableTimestamp: true
```

but do not get any metrics, user policy and permissions are good in logs there is nothing, when i try to enable debug i get this
```
2019/02/13 08:24:20 {
  EndTime: 2019-02-13 08:24:20.022910123 +0000 UTC m=+23.127186598,
  MetricName: "BucketSizeBytes",
  Namespace: "AWS/S3",
  Period: 86400,
  StartTime: 2019-02-11 08:24:20.022910469 +0000 UTC m=-172776.872813072,
  Statistics: ["Average"]
}
2019/02/13 08:24:20 {
  EndTime: 2019-02-13 08:24:20.022910123 +0000 UTC m=+23.127186598,
  MetricName: "BucketSizeBytes",
  Namespace: "AWS/S3",
  Period: 86400,
  StartTime: 2019-02-11 08:24:20.022910469 +0000 UTC m=-172776.872813072,
  Statistics: ["Average"]
}

```

but there is a lot of buckets in this region, it try to change region but no luck, can you point me what i do wrong?

**Comment by tsupertramp** [comment]
You need to add missing dimensions to your metrics:
```
        dimensions:
         - name: BucketName
           value: your-bucket
         - name: Storage­Type
           value: StandardStorage
```

This is happening in the background. Length defines the start point. Its the current Time - length in seconds. Period defines how many data points you use to calculate an average. If length is two days and period for example 1 day. Then you would get the average of those two points.

You can try out if you get the bucket through this command.

aws cloudwatch get-metric-statistics --metric-name BucketSizeBytes --namespace "AWS/S3"  --statistics Average --period 86400 --unit Bytes --region eu-west-1 --dimensions Name=BucketName,Value=YOUR-BUCKET Name=StorageType,Value=StandardStorage --start-time 2019-02-01T00:00:00Z --end-time 2019-02-02T00:00:00Z

I will rename your issue to solve it for more people then you. Sorry documentation and debugging user experience for static is not on the level i would like to have. Will fix this.

**Comment by tsupertramp** [comment]
https://github.com/ivx/yet-another-cloudwatch-exporter/issues/44

**Comment by dmitriy-lukyanchikov** [comment]
but i need to get all the buckets metrics, i do not filter by dimension, when i try to run similar config on prom/cloudwatch exporter i get all buckets metrics. can i archive the same functionality here?

**Comment by tsupertramp** [comment]
Interesting will check the code of prom exporter this evening and will try to debug why it is not working here.

**Comment by tsupertramp** [comment]
Sorry did not had time last evening. Will try this one.

**Comment by madAndroid** [comment]
We're experiencing this as well - only when we define a specific dimension does any data get picked up ... it would be good if we could define a regex for the dimension, for example:
```
static:
  - namespace: AWS/ElasticMapReduce
    region: eu-west-1
    dimensions:
    - name: JobFlowId
      value: .+
    metrics:
      - name: AppsFailed
        statistics:
        - 'Sum'
        period: 60
        length: 300
        delay: 300
```
