### ISSUE TITLE
no token found on elb sum metrics

### ISSUE THREAD

**Issue by thomasjungblut** [ivx/yet-another-cloudwatch-exporter#45]
Hey! Thanks for the great tool :)

Prometheus (we run 2.3.2) has some issues with scraping elb metrics with _sum suffix. My config looks like this:

```
  config.yml: |-
    discovery:
      exportedTagsOnMetrics:
        elb:
        - kubernetes.io/service-name
        - kubernetes.io/cluster/CLUSTER_NAME
      jobs:
      - type: "elb"
        region: eu-west-1
        searchTags:
          - Key: kubernetes.io/cluster/CLUSTER_NAME
            Value: owned
        metrics:
          - name: HealthyHostCount
            statistics:
            - 'Average'
            period: 60
            length: 300
          - name: UnHealthyHostCount
            statistics:
            - 'Average'
            period: 60
            length: 300     
          - name: HTTPCode_Backend_3XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true                   
          - name: HTTPCode_Backend_2XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: HTTPCode_Backend_4XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: HTTPCode_Backend_5XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: HTTPCode_ELB_5XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: RequestCount
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: BackendConnectionErrors
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: EstimatedProcessedBytes
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: Latency
            statistics:
            - 'Maximum'
            - 'Average'
            - 'Minimum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
```

You can check the resulting metrics with:
> cat metrics.txt | promtool check-metrics

which reveals this issue:

```
aws_elb_backend_connection_errors_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_estimated_processed_bytes_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_2_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_3_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_4_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_5_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_elb_5_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_request_count_sum: non-histogram and non-summary metrics should not have "_sum" suffix
```

Can we append some static suffix via config, or always append something to _sum*?

**Comment by thomasjungblut** [comment]
@tsupertramp just let me know what you think is the best approach to make this work, I'm happy to create a PR then :)

**Comment by tsupertramp** [comment]
Sorry for the late reply. Combination of sickness and vacation.

Wow interesting phenomenon - No quick idea.

I want to merge two prs the next days. I will look into that during these contribution hours as well.

Could you in the meantime please try out the following config:
```
          - name: HTTPCode_Backend_5XX
            statistics:
              - 'Sum'
            period: 300
            length: 300
            nilToZero: true
            disableTimestamp: true
```
