### ISSUE TITLE
Only some Application ELB Metrics collected

### ISSUE THREAD

**Issue by JohannesRu** [ivx/yet-another-cloudwatch-exporter#49]
Hey, 

We've been using the tool to get our classic ELB CloudWatch metrics into Prometheus. Works great thanks a lot!! 👏
As our architecture evolves we now have application ELBs as well whose metrics we want to track. 

1. In order to collect those I noticed an additional IAM permission had to be granted (could adjust that in the Readme via PR if this is intended, just let me know)
![image](https://user-images.githubusercontent.com/3695123/53838497-8a087d80-3f95-11e9-9bb4-58d386071237.png)

2. Unfortunately this still did not quite fix it for us. Only a few of the desired metrics are exported. 
![image](https://user-images.githubusercontent.com/3695123/53838588-c20fc080-3f95-11e9-9d3a-482a17c98dca.png)
In the AWS CloudWatch dashboard I do see values for all the metrics configured. I added the configmap below. Is there anything we do wrong?

Best regards and keep up the good work!
Johannes

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-config
data:
  config.yml: |-
    discovery:
      exportedTagsOnMetrics:
        elb:
        - kubernetes.io/service-name
        - kubernetes.io/cluster/my-cluster
        alb:
        - kubernetes.io/service-name
        - kubernetes.io/cluster/my-cluster
      jobs:
      - type: "elb" 
        region: eu-west-1
        searchTags:
          - Key: kubernetes.io/cluster/my-cluster
            Value: owned
        metrics:
          - name: RequestCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: BackendConnectionErrors
            statistics:
            - 'Sum'
            period: 60
            length: 300
      - type: "alb" 
        region: eu-west-1
        searchTags:
          - Key: kubernetes.io/cluster/my-cluster
            Value: owned
        metrics:
          - name: ActiveConnectionCount
            statistics:
            - 'Sum'
            period: 60
            length: 600
          - name: HTTPCode_ELB_5XX_Count
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: HTTPCode_ELB_4XX_Count
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: HTTPCode_ELB_3XX_Count
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: RejectedConnectionCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: TargetResponseTime
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: RequestCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: ClientTLSNegotiationErrorCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
```
