### ISSUE TITLE
List of dimensions to be fetched with metrics

### ISSUE THREAD

**Issue by Deepak1100** [ivx/yet-another-cloudwatch-exporter#73]
I needed the ELB and ALB metrics with load balancer name and AvailabilityZone dimension.
according to docs, I cannot specify list dimension without specifying the value.

even with value, if I try the same dimension with multiple values it's only giving metrics with last value. rest are ignored.
in below example, I will get metrics with one dimension value i.e which is specified last (ap-south-1a is ignored) 

```
 discovery:
   jobs:
     - type: "elb"
       region: ap-south-1
       searchTags:
         - Key: kubernetes.io/service-name
           Value: .*
       metrics:
         - name: HealthyHostCount
           statistics:
           - 'Minimum'
           period: 60
           length: 60
           delay: 120
           additionalDimensions:
             - name: AvailabilityZone
               value: "ap-south-1a"
             - name: AvailabilityZone
               value: "ap-south-1b"
         - name: UnHealthyHostCount
           statistics:
           - 'Maximum'
           period: 60
           length: 60
           delay: 120
         - name: RequestCount
           statistics:
           - 'Sum'
           period: 60
           length: 60
           delay: 120
           nilToZero: true
````

```
aws_elb_healthy_host_count_minimum{dimension_AvailabilityZone="ap-south-1b",dimension_LoadBalancerName="xxxxx",name="arn:aws:elasticloadbalancing:ap-south-1:xxxx:loadbalancer/xxxx"} 29
```

One more thing according to docs additional dimensions should work at job level but it's only working at each metrics level.

this works.
```
       metrics:
         - name: HealthyHostCount
           statistics:
           - 'Minimum'
           period: 60
           length: 60
           delay: 120
           additionalDimensions:
             - name: AvailabilityZone
               value: "ap-south-1a"
             - name: AvailabilityZone
               value: "ap-south-1b"
```
This doesn't work
```
  jobs:
    - type: "elb"
      region: ap-south-1
      searchTags:
        - Key: kubernetes.io/service-name
          Value: .*
      additionalDimensions:
        - name: AvailabilityZone
          value: "ap-south-1a"
        - name: AvailabilityZone
          value: "ap-south-1b"
      metrics:
.....
```
