### ISSUE TITLE
alb type discovers Network load balancers too but does not collect metrics

### ISSUE THREAD

**Issue by peimanja** [ivx/yet-another-cloudwatch-exporter#81]
I have this simple configuration.
```
discovery:
  exportedTagsOnMetrics:
    alb:
      - Name
  jobs:
  - type: "alb"
    region: us-west-2
    metrics:
      - name: UnHealthyHostCount 
        statistics: [Maximum]
        period: 60
        length: 600
```
It works great and it discovers 12 Load balancers that are running. 3 of these LBs are Network Load Balancers. when it comes to metrics, it only exposes metrics for the Application Load Balancers.

Is there a way to collect metrics for NLBs? or I am missing something here.

**Comment by thomaspeitz** [comment]
Hey @peimanja (@vdczzz @bheight-Zymergen as you upvoted) -  Added NLB. Would be nice if you try it out and give me some feedback. As i am not using them internally it is hard to test the real world use cases.

Greetings, Thomas

**Comment by thomaspeitz** [comment]
@peimanja - They are not prefixed with nlb if you use `type: "nlb"`? That would be a bug. Or do you still use `type: alb` and it works?

**Comment by peimanja** [comment]
> @peimanja - They are not prefixed with nlb if you use `type: "nlb"`? That would be a bug. Or do you still use `type: alb` and it works?

My bad! it is all good.
```
aws_nlb_info{name="arn:aws:elasticloadbalancing:us-west-2:*****:loadbalancer/net/prod-vault-cluster/33c0dc7c22f009bd",tag_Name="prod-vault-cluster"} 0
# HELP aws_nlb_new_flow_count_maximum Help is not implemented yet.
# TYPE aws_nlb_new_flow_count_maximum gauge
aws_nlb_new_flow_count_maximum{dimension_LoadBalancer="net/abp-concoursewindows-worker-lb/63158d07ac87a469",name="arn:aws:elasticloadbalancing:us-west-2:*******:loadbalancer/net/abp-concoursewindows-worker-lb/63158d07ac87a469"}
```

**Comment by peimanja** [comment]
Noticed couple issues:

- NLBs still shows up in ALB and ELB metrics:
```
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:******:loadbalancer/net/abp-concoursewindows-worker-lb"}
aws_elb_info{name="arn:aws:elasticloadbalancing:us-west-2:******:loadbalancer/net/abp-concoursewindows-worker-lb/63158d07ac87a469"}
aws_nlb_info{name="arn:aws:elasticloadbalancing:us-west-2:******:loadbalancer/net/abp-concoursewindows-worker-lb/63158d07ac87a469"}
```
- for NLB, metrics with one dimension like `new_flow_count` get collected but multiple dimensions  metrics such as `HealthyHostCount` and `UnHealthyHostCount` are not getting collected. Even when specifying `additionalDimensions` and setting it to `LoadBalancer` or `TargetGroup` or both like:
```
  - type: "nlb"
    region: us-west-2
    additionalDimensions: [LoadBalancer, TargetGroup]
    metrics:
      - name: HealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 600
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 600
```
Same metrics are getting collected as expected for ALB even without setting the `additionalDimensions`:
```
  - type: "alb"
    region: us-west-2
    metrics:
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 600
  - type: "alb"
    region: us-east-1
    metrics:
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 600
```
