### ISSUE TITLE
Unable to scrape S3 request metrics e.g. AllRequests

### ISSUE THREAD

**Issue by nhinds** [ivx/yet-another-cloudwatch-exporter#85]
S3 [request metrics](https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html#s3-request-cloudwatch-metrics) don't appear to have a `StorageType` dimension, just `BucketName` and `FilterId`. I can *add* a `FilterId` dimension with the `additionalDimensions` setting, but I can't seem to remove the default `StorageType=AllStorageTypes` dimension from the S3 job. Seems similar to #78, but request metrics require the additional dimension `FilterId`.

```
discovery:
  jobs:
  - type: s3
    region: us-west-2
    metrics:
    - name: AllRequests
      statistics: [Sum]
      period: 60
      length: 6000
      delay: 600
      additionalDimensions:
      - name: FilterId
        value: MyFilterId
```

```
2019/07/29 05:38:41 CLI helper - aws cloudwatch get-metric-statistics --metric-name AllRequests --dimensions Name=BucketName,Value=my-bucket-nameName=StorageType,Value=AllStorageTypesName=FilterId,Value=EventLogs --namespace AWS/S3 --statistics Sum --period 60 --start-time 2019-07-29T03:48:41Z --end-time 2019-07-29T05:28:41Z
```

When running the command from the "CLI helper" debug logs (and adding the missing spaces), there are no results. Removing the `Name=StorageType,Value=AllStorageTypes` dimension does return data.

I see at one point in #47 there was a condition wrapped around the "AllStorageTypes" dimension where it wouldn't be added if someone had specified additional dimensions, but that condition was later removed. Could that condition be added back, or a separate option to remove default dimensions be added to the metric? e.g.

```
    - name: AllRequests
      statistics: [Sum]
      period: 60
      length: 6000
      delay: 600
      additionalDimensions:
      - name: FilterId
        value: MyFilterId
      includeS3StorageTypeMetric: false
```
