### ISSUE TITLE
classic ELB configuration, sporadic zero values

### ISSUE THREAD

**Issue by hcbraun** [ivx/yet-another-cloudwatch-exporter#98]
Hi,
thank you for this great free software! Sorry for posting this here. I am not sure if this is really a bug, a misconfiguration or AWS limitation. 

My configuration is below. I am monitoring all metrics on classic ELBs. For cost reasons i scrape every 60s with Prometheus. About once per day i see all metrics on all ELBs dip down to zero. To avoid this i increased length and delay to 240 and then 300 without success. Further increasing the delay is not really an option. I rather have sporadic zero values then a huge delay. 

Is there anything else i can do to avoid the zero values? 
If yace could report null instead of zero on these occasions, then i could handle this in the backend (Grafana / Prometheus alerts)

Thank you!

```
- type: elb
...
    metrics:
      - name: HTTPCode_Backend_2XX
        statistics:
        - 'Sum'
        period: 60
        length: 180
        delay: 180
        nilToZero: false
        addCloudwatchTimestamp: false
      - name: HTTPCode_Backend_3XX
        statistics:
        - 'Sum'
        period: 60
        length: 180
        delay: 180
        nilToZero: false
        addCloudwatchTimestamp: false
...
```

**Comment by thomaspeitz** [comment]
Hey :)

So length should be 300 as classic elbs are only written every 5 minutes. Period should be 300 as well. Delay should be not set in this case. This should work. Could you please try out and tell me if it worked? :)

Greetings, Thomas

**Comment by hcbraun** [comment]
Hi Thomas!
I changed my config and updated to v0.14.1-alpha: 
```
      - name: HTTPCode_Backend_2XX
        statistics:
        - 'Sum'
        period: 300
        length: 300
        nilToZero: false
        addCloudwatchTimestamp: false
```
It works, but does not solve the zero value issue. I am getting graphs like this:
![2019-09-27-104557_1440x411_scrot](https://user-images.githubusercontent.com/1728041/65756189-d9babc00-e114-11e9-9177-cb46c5c4db36.png)

Thank you!

Should be < and not <= at:
https://github.com/ivx/yet-another-cloudwatch-exporter/blob/1d387b190848e3d7b8d56ea8f8983631ae52b107/config.go#L78
